### ISSUE TITLE
Tank gauges sometimes trail behind the actual remaining capacity

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1003]
Customer [report](https://community.victronenergy.com/questions/279997/venus-os-v3408-available-for-testing.html): "Randomly the fill bar does not appear on a tank or several tanks, note black water at 27%. This has occurred viewing gui2 through VRM and on the Cerbo GX Touch. Screenshots taken a few minutes apart."

![image](https://github.com/victronenergy/gui-v2/assets/2203667/8649a4c8-8023-453f-8d7a-56126947535c)
![image](https://github.com/victronenergy/gui-v2/assets/2203667/ebb908cf-0201-4607-8451-4d1ae1b22ea5)
![image](https://github.com/victronenergy/gui-v2/assets/2203667/3e06216b-e266-45d8-82a9-088b1977dd7c)

Also [reported](https://community.victronenergy.com/questions/279997/venus-os-v3408-available-for-testing.html?childToView=283848#answer-283848) with V3.40~13: "V3.40~13is still throwing a few inconsistent bar charts for the levels on both web view and the Cerbo touch 50 but improved from ~8.".

**Comment by chriadam** [comment]
Can reproduce.  The value in BarGauge.qml goes to NaN for some reason in some cases.

**Comment by chriadam** [comment]
... but sometimes even when it isn't NaN, the rectangle doesn't render, even though the "nextPos" value is calculated correctly.  Will investigate further :-/

**Comment by jpetrell** [comment]
Saw this when looping through the tank configurations on the latest main with the mock backend: 
![image](https://github.com/victronenergy/gui-v2/assets/2203667/a99b93ad-e303-4bcc-9b8a-e3d4f533b581)
