### ISSUE TITLE
Tank gauge drawn outside the container

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1017]
[Reported](https://community.victronenergy.com/questions/270759/venus-os-v3401-available-for-testing.html) by the customer. Looks like the item is trying to horizontally center two gauges with the right one being invisible.

![image](https://github.com/victronenergy/gui-v2/assets/2203667/78717620-096a-48de-9f9a-723fedc45240)

**Comment by jpetrell** [comment]
Reviewed the code in detail, not sure how the issue can reproduce with the latest code. If `mergeTanks=true` and `count=2` should be seeing two gauges on the LPG-Right gauge group item and the gauge width should be smaller. If `mergeTanks=false` and `count=2` there should be only one gauge per tank item with each gauge horizontally centered on the tank item background.

Asked the community member if they can still reproduce with the latest v3.40~13 release.

**Comment by jpetrell** [comment]
Still [reproduces](https://community.victronenergy.com/questions/279997/venus-os-v3408-available-for-testing.html?childToView=285923#answer-285923) to the customer (wizwaretech): "I see no post for 3.40~15, so I'll put this here. The same graph display issues exist, intermittently"

![image](https://github.com/victronenergy/gui-v2/assets/2203667/4fbe70d3-723c-472e-9355-38dc6813e91f)

**Comment by jpetrell** [comment]
[Customer](https://community.victronenergy.com/comments/286686/view.html): "I have to say that the bars on the level display are still showing some issues, see LPG Bow and LPG Stern. These are Bluetooth Mopeka sensors and when I opened the level display the LPG Stern sender had disconnected and when it reconnected whilst the level display was open and the display had to change from 4 to 5 tanks, the bar became displaced."
![image](https://github.com/victronenergy/gui-v2/assets/2203667/4b55e305-8682-4c22-8573-54a9d5cce4dd)

**Comment by chriadam** [comment]
I tried to repro using mock backend, adding a "flaky" tanks config.  Whether the tank was removed and re-added, or whether the tank merely set its device instance to -1 and back again, I could not reproduce the case mentioned in this report.

I tried both with my recent clipping-bar-gauge commits, and without.  Without the clipping bar gauge commits, I saw the previous issue (the double-animation and non-rendered foreground), but not the issue described here in this report.

Note that the issue in this report is NOT just the shader effect, it's the whole TankGauge as it includes the background and the separator bars.  So I think this one must be some sort of property states issue, but I was unable to reproduce with my mock (see attached diff).

[mock-flaky-tanks.diff.txt](https://github.com/victronenergy/gui-v2/files/15399089/mock-flaky-tanks.diff.txt)

**Comment by chriadam** [comment]
I suspect that the width of the Loader of the "other" tank in the model isn't being set to zero appropriately.  I've created PR#1122 which should fix it if that is the issue.  But without being able to reproduce the issue I simply am not sure.
