### ISSUE TITLE
Improve UI for AC in/out when feeding back to grid

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1041]
When ESS feed-in is enabled, negative power for the AC in/out indicates that the AC is feeding back to the grid. In this case, gui-v2 can:

- drop the minus sign in the Brief and Overview pages
- show the direction icon in the Overview box; this is already present in the Brief gauge
- use zero as the minimum when feed-in is disabled

It's possible for negative values to occur even when feed-in is disabled, but in this case it's just noise, and the minus sign can be removed.

**Comment by blammit** [comment]
For reference, drop the minus signs here:


![image](https://github.com/victronenergy/gui-v2/assets/1260099/d0e5db3b-c3ba-45d1-b7e2-27c09e06f254)
![image](https://github.com/victronenergy/gui-v2/assets/1260099/436f7631-8c1f-4d43-864d-15b06976198c)

**Comment by mr-manuel** [comment]
Is this already somewhere in a branch with the arrow and green color?

**Comment by mr-manuel** [comment]
Is something similar also planned for the Inverter/Charger box for noting the difference between inveting and charging?

**Comment by blammit** [comment]
> Is this already somewhere in a branch with the arrow and green color?

Yes, this is already done for the Brief page in `main`.

**Comment by blammit** [comment]
> Is something similar also planned for the Inverter/Charger box for noting the difference between inveting and charging?

I don't think there is at the moment. Perhaps @jepefe can comment more on whether that will happen.

**Comment by mr-manuel** [comment]
Strange, I'm using the `v0.2.19`, which is the latest main build. Has it to be enabled?

![venus-os-gauges](https://github.com/victronenergy/gui-v2/assets/12592765/2df153de-dcd5-454c-a4de-2e0cea8629f3)

**Comment by mr-manuel** [comment]
Now I discovered, that it's only shown, if `AC-coupled PV - feed in excess` AND `DC-coupled PV - feed in excess` is enabled. Shouldn't it be enabled if  `AC-coupled PV - feed in excess` OR `DC-coupled PV - feed in excess` is enabled?

**Comment by blammit** [comment]
I'm not sure about that criteria, but it's currently shown when power < 0 and:

com.victronenergy.system/Hub = 4
com.victronenergy.settings/Settings/CGwacs/OvervoltageFeedIn = 1
com.victronenergy.settings/Settings/CGwacs/PreventFeedback = 0

**Comment by mr-manuel** [comment]
`com.victronenergy.system/Hub = 4` --> Checks if the system has ESS
`com.victronenergy.settings/Settings/CGwacs/OvervoltageFeedIn = 1` --> `DC-coupled PV - feed in excess = Enabled`
`com.victronenergy.settings/Settings/CGwacs/PreventFeedback = 0` --> `AC-coupled PV - feed in excess = Enabled`

I think here is to clarify, if `OvervoltageFeedIn ` AND `PreventFeedback ` needs to be met or only one of them. In my eyes only one of this two is needed.

**Comment by jepefe** [comment]
@blammit 

```
com.victronenergy.system/Hub == 4 && (com.victronenergy.settings/Settings/CGwacs/OvervoltageFeedIn == 1 || 
com.victronenergy.settings/Settings/CGwacs/PreventFeedback == 0)
```

**Comment by jepefe** [comment]
> > Is something similar also planned for the Inverter/Charger box for noting the difference between inveting and charging?
> 
> I don't think there is at the moment. Perhaps @jepefe can comment more on whether that will happen.

The battery has a label that says 'Charging' or 'Discharging', so it must be clear enough on the current implementation. Or is it not?

**Comment by mr-manuel** [comment]
It is clear. It would been only for consistency, if one gauge turns green when negative, it would be obvious that also the other has the same behaviour.

On the overview page you have charging and discharging, but not on the brief page.

**Comment by blammit** [comment]
Thanks, will make that fix as part of these changes.

**Comment by blammit** [comment]
> It is clear. It would been only for consistency, if one gauge turns green when negative, it would be obvious that also the other has the same behaviour.

> On the overview page you have charging and discharging, but not on the brief page.

@jepefe what do you think? Should the AC load bars turn green when the system is charging? If so, please let me know which `/SystemState/State` values should be matched for the "charging" case.
