### ISSUE TITLE
Brief page: Side panel grid graph

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#1060]
Shouldn't the graph for the grid start in the middle, if grid feed in is enabled?

![grafik](https://github.com/victronenergy/gui-v2/assets/12592765/3e162f39-dc4d-4d6a-a0b4-99ce8ba27d31)

Like this:

![grafik](https://github.com/victronenergy/gui-v2/assets/12592765/1aace12c-ad3f-4a8d-a602-26d34f491da1)

**Comment by blammit** [comment]
Yes it should, thanks!
