### ISSUE TITLE
With 5 side panel widgets the last widget gets clipped by the nav bar

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1061]
![image](https://github.com/victronenergy/gui-v2/assets/2203667/e6e65fbf-6c31-48d4-b3a1-46cae6febc38)

**Comment by blammit** [comment]
Not sure what we want to do here. Fade out the last widget and then fade it back in when the nav bar disappears?

**Comment by kwindrem** [comment]
If you can keep the nav bar visible then the side panel should either compress as happens with the Overview page or allow scrolling vertically to expose additional widgets.

If the nav bar always disappears after a period of inactivity then what happens in this scenario is of less importance. I'd just leave it the way it is.

**Comment by jpetrell** [comment]
Serj: "Dimensions and spacing are not respected in implementation. 5 widgets should fit"
![image](https://github.com/victronenergy/gui-v2/assets/2203667/f613f1f8-b545-429a-a55c-95c982db3dbd)
