### ISSUE TITLE
Brief page: Side panel grid graph fill

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#1073]
The grid graph should be filled to zero and not to the bottom.

Reference to https://github.com/victronenergy/gui-v2/pull/1065#issuecomment-2117300315

## Current
![331313346-3e162f39-dc4d-4d6a-a0b4-99ce8ba27d31](https://github.com/victronenergy/gui-v2/assets/12592765/9ed462e8-0ca3-4793-9aff-f259ae563eb6)

## Expectation
![331313847-1aace12c-ad3f-4a8d-a602-26d34f491da1](https://github.com/victronenergy/gui-v2/assets/12592765/e44cbb39-a45f-4ff8-ab64-aec935288be3)

**Comment by blammit** [comment]
@jepefe any thoughts on this? The current gui-v2 design uses a graph design that is different from the one in VRM portal.

**Comment by kwindrem** [comment]
Yes all graphs and gauges should fill from zero like is shown in the expectation. Filling to the minimum displayed on the graph/gauge doesn't make any sense.

**Comment by jepefe** [comment]
@blammit Is it is not too much work, please change it the filling to match vrm.

**Comment by blammit** [comment]
@DanielMcInnes do you want to look into this one, since you're more familiar with the LoadGraph?
