### ISSUE TITLE
show module level alarms only if they are valid

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1076]
gui-v1 commit: 8ed88280dae261b6ebcc47ac35f19b1be21066ea

**Comment by jpetrell** [comment]
gui-v1 hides "Module level alarms" navigation list item if there are no module alarms defined by checking the first error "/Diagnostics/Module0/Id", gui-v2 already hides  "Module level alarms" navigation list item if there are no errors 0-9 "/Diagnostics/Module[0-9]/Id".
