### ISSUE TITLE
add support for RS system

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1077]
gui-v1 commit: 8981fa9bc8ac55f559b7dba569d9af5d7332c26c

**Comment by mpvader** [comment]
@izak , on gui-v2, on the overview page, there is an action when the user clicks the inverter/charger icon in center top.

Is this a good rule for @blammit to implement?

1. if multiple AC systems and/or Multis, show a list of VE.Bus + AC Systems
2. if only one VE.Bus -> no list, but VE.Bus page opens
3. if only one AC system -> no list, but AC system page opens
4. if only one RS unit -> no list, and also no AC system, but RS page opens.

**Comment by izak** [comment]
There is always an acsystem, even if there is only one Multi-RS, so rule 4 is not necessary.

Also, systems with plain inverters (not inverter/chargers) probably need to be accommodated? So can probably be consolidated to:

1. If Multiple AC-systems, Multis or other inverters, show a list
2. If only AC-system, VE.Bus or Inverter, open the relevant page directly.

**Comment by blammit** [comment]
As part of this integration in gui-v2, discussed that when the Inverter/Charger overview widget is clicked, instead of 
showing a list of these services:

- inverter
- vebus 
- multi

Show these instead:

- inverter
- vebus
- acsystem

And any multi services can be accessed via the acystem instead.

**Comment by mpvader** [comment]
@izak for my item 4: what is the advantage of showing acsystem over hiding it for the user if he has just one RS?

Having AC system adds levels & complexity in the UI

**Comment by izak** [comment]
@mpvader If it is just about simplifying the UI, then indeed, there is no reason to show the acsystem instead of the RS when there is only one. I don't have a preference here.

**Comment by mpvader** [comment]
@izak Should Bea “hide” the ac system in that case? Or you take it out of the dbus?

**Comment by mpvader** [comment]
understand @izak ! thanks.

@blammit all clear to you now?

**Comment by blammit** [comment]
Okay, so I think it is as per my previous comment -- when clicking the Inverter/Charger box, we will show a list of these:

- inverter
- vebus
- acsystem

And the user will click on the acsystem to get to the RS devices.

The control cards still show the RS devices rather than acsystems, i.e. there is one control card for each RS device (along with other control cards for `inverter` and `vebus` devices).

**Comment by mpvader** [comment]
Hi Bea, yes but show the list only of there is multiple entries after compiling the list. If there js just one entry (which is the case for 99% of all systems) then I want to the user to go straight to that entry.

and, I think you know this but just to make sure: clicking the AC system entry takes the user to the AC System page. Which has somewhere in its submenus a list of Multi RS-es.

Control cards: one per AC system is needed. Not one per Multi.

**Comment by blammit** [comment]
> Hi Bea, yes but show the list only of there is multiple entries after compiling the list. If there js just one entry (which is the case for 99% of all systems) then I want to the user to go straight to that entry.
> and, I think you know this but just to make sure: clicking the AC system entry takes the user to the AC System page. Which has somewhere in its submenus a list of Multi RS-es.

Yes, this is the implemented solution 👍 If there is only one item, then we don't show the list. (Sorry, should have clarified in the previous comment.) And yes, clicking the AC system entry goes to the AC system page, which contains the "Devices" entry with a list of Multi RS devices.

> Control cards: one per AC system is needed. Not one per Multi.

That makes sense. Fixed this now in https://github.com/victronenergy/gui-v2/pull/1199

**Comment by chriadam** [comment]
As per testing on Wednesday:
1) Could not change inverter mode via control card, but could via device list.  The mode was shown correctly in the control card if it was changed via device list, but could not be changed via control card.  Tested with "GR 3phase without EM".
