### ISSUE TITLE
PageBatteryDetails: hide unused items

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1087]
gui-v1 commit: 8118d8f243bef995b5c8127d5520417668144c82

**Comment by chriadam** [comment]
As per testing on Wednesday:
1) Separator should be hidden from e.g. "Lowest cell voltage" etc list items, if the cell id is unknown.
2) If no battery details are visible / valid, we should hide (or at least disable) the "Details" drilldown in battery device page.

**Comment by blammit** [comment]
> If no battery details are visible / valid, we should hide (or at least disable) the "Details" drilldown in battery device page.
This is fixed by https://github.com/victronenergy/gui-v2/issues/1201

**Comment by blammit** [comment]
> Separator should be hidden from e.g. "Lowest cell voltage" etc list items, if the cell id is unknown.

This is of a lower priority and takes more work to resolve due to the way that ListQuantityGroup is built at the moment. I have a created an issue with some related remarks [here](https://github.com/victronenergy/gui-v2/issues/1338), so we can close this task as the main issue has been resolved.
