### ISSUE TITLE
ess: improve peak shaving menu

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1090]
gui-v1 commit: 20de39961eb9f0faf24162b4c520f4f9ef290a1f

    Split the peak shaving options into a sub-menu, as the main menu
    is getting a little crowded now. Import limit option is only
    available if the assistant on the Multi is capable. The menu also
    reacts correctly to sites running with/without a grid meter,
    or where keepBatteriesCharged is set.

**Comment by blammit** [comment]
Fixed by https://github.com/victronenergy/gui-v2/pull/1155
