### ISSUE TITLE
PageTemperatureSensor: Show battery status along with battery voltage

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1092]
gui-v1 commit: 00836db21bb773fc0c928fae3f7392491b28c1bb
    PageTemperatureSensor: Show battery status along with battery voltage
    
    Status is only visible when the "/Alarms/LowBattery" path is supported
    by the sensor.

**Comment by jpetrell** [comment]
Already fxed, duplicate to #751.
