### ISSUE TITLE
"MultiRS" and "charger" settings pages are not yet implemented

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1093]
I'm not sure why these are still hooked up to PageNotYetImplemented.qml in DeviceListPage

**Comment by blammit** [comment]
There was a discussion in https://github.com/victronenergy/gui-v2/issues/328 that these were not required for implementation yet. But maybe that has changed? Need to confirm with @mpvader

**Comment by mpvader** [comment]
Hey, yes its changed - or at least about to. Izak is finishing up his implementation of it in gui-v2.

**Comment by blammit** [comment]
@mpvader did you mean gui-v2? I checked with @izak and he said he has implemented updates in gui-v1. I can look at porting those to gui-v2.

**Comment by mpvader** [comment]
Yes, good catch! Amended. Pls do

**Comment by blammit** [comment]
Changes merged.

**Comment by chriadam** [comment]
https://github.com/victronenergy/gui-v2/pull/1292/files fixes this issue according my testing

**Comment by chriadam** [comment]
Fixed.
