### ISSUE TITLE
Update logic for AC input source

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1100]
Compare gui-v1' 'getAcSourceName(type)' with gui-v2 'getAcSourceName(type)'

**Comment by chriadam** [comment]
As per testing on Tuesday:
1) When using mock #7 which has a shore input but no second ac input, go to: settings -> display and language -> minimum and maximum gauge ranges.  Note that the second ac input should say "not available" in parentheses rather than empty string.  (Or hidden altogether?)
