### ISSUE TITLE
Quantity table missing on the Solar charger settings

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1118]
[Reported](https://community.victronenergy.com/questions/279997/venus-os-v3408-available-for-testing.html) by the customer, "With 3.40~10, details of solar (MQTT Solar) are not seen any more"

![image](https://github.com/victronenergy/gui-v2/assets/2203667/3477ee05-f4c1-4d32-9685-0a7aeee702c5)

**Comment by blammit** [comment]
I'm having trouble reproducing this one; have tried several different installations on VRM. It appears that the QuantityTableSummary is producing invalid data, and therefore it has no children and the height is shrunk, but it's strange that even the default text (e.g. "--" if the voltage is not present) is not appearing.

**Comment by jpetrell** [comment]
> I'm having trouble reproducing this one

Reducing priority. I can check at some point too, if cannot repro either will close.

**Comment by jpetrell** [comment]
No reply from the customer yet to the comments.

**Comment by blammit** [comment]
Can reproduce this on the system reported by https://github.com/victronenergy/gui-v2/issues/1280. Closing this as duplicate.
