### ISSUE TITLE
Overview page CPU consumptions has grown from 34% to 44% on Cerbo GX

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1126]
CPU consumption of the Overview page has regressed since [March](https://github.com/victronenergy/gui-v2/issues/639#issuecomment-2022222312), from 34% to 44%. Even when the electron animations are disabled the CPU usage hovers around 25%, even though nothing is seemingly animating.

Expected: Without electron animations the CPU consumption is only few percentages.

Minimal animation increases CPU consumption everywhere to 25% like before so doesn't seem that any substantial off screen elements outside the current page are drawn (like the virtual keyboard before). Levels, Notification and Settings pages still only see 1-2% CPU consumption like before so are also good. The Brief page is seeing now 13% CPU consumption, would be nice to understand what is causing it, could be the same root cause (e.g. related to gauges) as here.

**Comment by mr-manuel** [comment]
Short question to this. There were once little bubbles on the Overview page when the battery was loaded. Was this completely removed even for the wasm build? I liked it very much and in a browser there is normally more power :)

**Comment by jpetrell** [comment]
Discussed with @mpvader there are more important items to tackle right now, reducing priority.

**Comment by jpetrell** [comment]
> Discussed with @mpvader there are more important items to tackle right now, reducing priority.

Actually meant this comment for #1125, had wrong browser tab open sorry. Would be nice to understand where does the CPU increase come from, and fix the regression if it is an easy fix.

**Comment by chriadam** [comment]
https://github.com/victronenergy/gui-v2/pull/1171 reduces things somewhat.  There's still plenty to do.  See comments in PR.

**Comment by mpvader** [comment]
nice!
