### ISSUE TITLE
VeBus and InverterCharger settings expose same device details, but in slightly different order

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1137]
Actual result: VeBus and InverterCharger settings expose the same device details, but in slightly different order. They use different DBus services and seems they have have been implemented separately, leading to small differences in the way the information is presented.

Expected result: Device details should be presented in consistent manner. Ultimately both display the same information.

![image](https://github.com/victronenergy/gui-v2/assets/2203667/2717d7aa-adc2-4771-9b99-67d485a76e1c)

**Comment by blammit** [comment]
Yeah, this is a bit odd. This is happening because `OverviewInverterChargerPage` comes from the Figma design for the vebus drilldowns, while `PageVeBus.qml` is the ported version from gui-v1. 

Perhaps the Settings 2.0 will lead to an updated design for `PageVeBus.qml`?

**Comment by blammit** [comment]
Discussed this with @jepefe . The overview drilldown is supposed to show generic information that is relevant to VE.Bus devices, RS systems and inverters, whereas `PageVebus.qml` only provides VE.Bus information.
