### ISSUE TITLE
Multi RS solar device duplicated in Device List and not listed in "RS devices"

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1142]
Tested with Groningen MultiRS test installation. 

The MultiRS solar device is duplicated in the Device List, and also is not listed as part of a "RS devices" settings list item in the solar device settings, as per gui-v1.

The "RS devices" will be addressed by #1077, but verify that the Device List duplication is fixed as well.

**Comment by podarok** [comment]
My MultiRS is listed in RS Devices
![image](https://github.com/victronenergy/gui-v2/assets/563412/e7760d6c-a3c3-4d29-bcf2-f55fbd5f837f)

![image](https://github.com/victronenergy/gui-v2/assets/563412/f92409a6-5882-4440-a123-79b4863d1992)

Venus OS version
v3.40~17
![image](https://github.com/victronenergy/gui-v2/assets/563412/0361df8b-cf5d-4d4f-baff-871a3b6cc999)


But it is duplicated in gui-v2, which is an issue
![image](https://github.com/victronenergy/gui-v2/assets/563412/bbf755a9-1193-4fa0-8751-952342e73a43)

**Comment by blammit** [comment]
PR merged, closing.

**Comment by blammit** [comment]
@podarok Thanks for the screenshots -- the Device List should now be fixed.

**Comment by podarok** [comment]
> @podarok Thanks for the screenshots -- the Device List should now be fixed.

Is there a new Venus OS beta build where I can check this?

**Comment by jpetrell** [comment]
> Is there a new Venus OS beta build where I can check this? @blammit

We will tag a new gui-v2 release end of this week, after which it will be picked for the next [Venus OS beta](https://community.victronenergy.com/questions/279997/venus-os-v3408-available-for-testing.html) release in few days.

**Comment by blammit** [comment]
@podarok this change hasn't been released yet -- hopefully the next one!
