### ISSUE TITLE
Wrong gauge values when some phases consume while others feed in

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1144]
When consuming on one phase and feeding in on another, the gauge values for the feed-in phases are zero.

![image](https://github.com/victronenergy/gui-v2/assets/1260099/e823f585-864d-4564-a78d-b2a85e38e973)

**Comment by blammit** [comment]
Would be nice to have a test system for this, as I cannot reproduce in mock mode.

@ReinvdZee would it be possible to have a python script with a recording to test this situation, where some phases are negative while others are positive?

**Comment by DanielMcInnes** [comment]
I can reproduce this issue at "GRN - RS 3phase without EM". It is caused by clamping the power value when grid feedback is disabled. I removed the clamping, and gui-v2 showed the same gauge values as gui-v1. I'll check for clamping elsewhere in the codebase

**Comment by chriadam** [comment]
If grid feedback is disabled, why should any negative power values be seen?

**Comment by chriadam** [comment]
Or, to ask the question a different way: is the system not disabling grid feed-in properly, in the case where the user specifies that grid feed-in should be disabled?

**Comment by blammit** [comment]
@jepefe we're seeing an installation (RS 3phase without EM) with these settings:

`/Hub4` is not set
`/Settings/CGwacs/OvervoltageFeedIn` = 0
`/Settings/CGwacs/PreventFeedback` = 0

This should mean that feed-in is not enabled. As mentioned [here](https://github.com/victronenergy/gui-v2/issues/1041#issuecomment-2106903897), this is the test, for whether feed-in is enabled:

```
com.victronenergy.system/Hub == 4 && 
(com.victronenergy.settings/Settings/CGwacs/OvervoltageFeedIn == 1 || 
com.victronenergy.settings/Settings/CGwacs/PreventFeedback == 0)
```

So on the installation I would expect power/current values to always be positive (or can be ignored if negative). However, the installation is producing negative values, and VRM portal is showing those as feed-in values.

What should gui-v2 be doing here? Should the feed-in conditional be modified?

**Comment by DanielMcInnes** [comment]
@chriadam , possibly the system is not disabling grid feed-in properly, but that is another issue. We should still be displaying the 'real' values showing grid feedback, and matching gui-v1's behaviour.

**Comment by chriadam** [comment]
That's true, I guess, if something wrong is happening it's better to SHOW the user that something is wrong.

**Comment by blammit** [comment]
The checking of whether feed-in is disabled is something new introduced in gui-v2, so perhaps it's an unreliable check at this stage. And in the interests of aligning with VRM Portal and gui-v1 I think it'd be better to drop it for now.

I think really, the values should be clamped in the backend, and not at the UI level.

**Comment by jepefe** [comment]
The problem is that those paths works for VE.Bus Inverters but probably not for RS inverters.

@izak Can you confirm which paths shall we look into to determine if ESS is enabled for Multi RS? Is there a generic way to check it for both, RS & VE.Bus?

**Comment by izak** [comment]
@jepefe Technically ESS is always "enabled" for the Multi-RS. There is nothing special you have to do, it always has the capability. There is [an issue][1] for providing a single place that will tell you if feed-in is expected or not.

Overall, I would agree with the earlier statement that hiding feed-in from the user (aka clamping) should not be done. In a three phase system that balances the total of the phases to a positive value, it is still possible to have some of your phases negative.

[1]: https://github.com/victronenergy/venus-private/issues/370
