### ISSUE TITLE
Invert gauge bars when feed-in is enabled

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1145]
![image](https://github.com/victronenergy/gui-v2/assets/1260099/9f3f7dae-8c62-4ea9-a3f4-596ac699ff8d)

The confusion arises because when feed-in is enabled, the power/current is negative, so the gauge bars move in the opposite direction. We could use an absolute value for the gauge instead when feed-in is enabled, so that a longer green bar indicates more power being fed back to the grid, rather than less.

**Comment by mr-manuel** [comment]
Ask the user to switch to amps display instead of watts to see the difference. Could be the same as https://github.com/victronenergy/gui-v2/issues/1045.

**Comment by mr-manuel** [comment]
Please do not change it. I think that would be even more confusing. Let's try to solve the other issue first and see if it also solves this one.

**Comment by mpvader** [comment]
Hey @mr-manuel , how is making the light green section of the bar longest for the phase that feeds most power in not good?

i see how the other issue can make things extra confusing, but still it looks like there is a small bug here?

**Comment by mr-manuel** [comment]
I meant that it could be confusing if you only change colors and use absolute values. At least it would confuse me. A nice thing would be, if the bar is starting at 0 and not at minimum. Therefore it should go down or up.

**Comment by mr-manuel** [comment]
I re-read everything and maybe I misunderstood. I think this would be the clearest option. Also for the gauges on the overview page, if feed in is enabled.

![grafik](https://github.com/victronenergy/gui-v2/assets/12592765/5a45de44-3e8f-4187-858e-8fc7e0818f29)

![grafik](https://github.com/victronenergy/gui-v2/assets/12592765/c183e9ff-be22-4980-a651-8ce7f941a214)

**Comment by jepefe** [comment]
The idea is to use absolute AC IN values for the gauge and change the color of the bar to green when values are negative which means feeding back the grid. 

The advantages are:
- Easy to read from the distance as it uses the whole gauge
- Don't need to learn to read a split or a bidirectional gauge
- Keeps UI coherence
- Simple implementation

**Comment by kwindrem** [comment]
I agree with mr-manual. The color difference is not sufficient to differentiate consumption vs feed-in to an unskilled user. So please revisit this after gui-v2 v1.0 is released. Thanks.
