### ISSUE TITLE
dbus-generator: rename `/Autostart` path and more

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1147]
Check if we need to do the following changes to gui-v2. 

See https://github.com/victronenergy/venus/issues/1267

**Path `/Autostart`**
Rename `/AutoStart` to `/RemoteStartModeEnabled` on the Genset AC in model page. 

**Toast**
When the user sets "mode" to "on", but the `/RemoteStartModeEnabled` is 0, the user is notified that the genset autostart feature must be enabled on the genset panel:
![image](https://github.com/victronenergy/gui-v2/assets/38864570/72ab3c18-7dae-4151-9201-4a9013d472ca)

Change the toast text to: 
"Unable to start the genset because its remote start functionality is disabled. Enable it on the genset control panel"

**Auto start/stop menu visibility**
In the genset menu, the "Auto start/stop" submenu will only be visible when setting the mode to "Auto start/stop". This menu should always be visible.

![image](https://github.com/victronenergy/gui-v2/assets/38864570/61920888-75cb-4121-aa00-960f8f3b8831)

**Comment by DanielMcInnes** [comment]
@ReinvdZee I think this is blocked until the dbus path name changes are done. I've committed untested gui-v2 changes to 1147-dbus-generator-rename-autostart-path-and-more.

**Comment by DanielMcInnes** [comment]
> Check if we need to do the following changes to gui-v2.
Yes, looking at the proposed gui-v1 changes, there will be corresponding changes required for gui-v2

**Comment by mpvader** [comment]
I’ve removed the milestone; good that its done -This has to wait till all similar changes elsewhere in Venus OS are done

**Comment by mpvader** [comment]
Hey @DanielMcInnes , its probably best to decouple these three changes:

1) path rename waits and is blocked
2) toast with text change can be merged (or keep it waiting of you prefer that to not do more for v1.0.0 - its not at all crucial)
3) changing menu structure is part of #1220

**Comment by jhofstee** [comment]
the Path renames are included in Venus v3.50~1

**Comment by ReinvdZee** [comment]
@DanielMcInnes (or @chriadam / @blammit), The `/AutoStart` rename is included per Venus v3.50~1, can you also merge the [`/AutoStart` rename branch](https://github.com/victronenergy/gui-v2/tree/1147-dbus-generator-rename-autostart-path-and-more)? We'd like to have it included in the next release.

**Comment by DanielMcInnes** [comment]
@ReinvdZee , will do
