### ISSUE TITLE
Virtual keyboard doesn't open when accessing gui-v2 on the VRM website (Android)

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1150]
Open gui-v2 on an Android device from VRM website. Tap any text field.

Expected result: Virtual keyboard opens, allowing you to input text.

Actual result: Blinking cursor becomes visible, indicating the text field thinks it has focus, but no keyboard appears.

Text input works on desktop browsers and the virtual keyboard opens like expected on iPadOS (and thus likely also iOS, but haven't verified).

Also reported by the [customers](https://community.victronenergy.com/questions/279997/venus-os-v3408-available-for-testing.html): 
- "Above - focus on input widget to rename Shunt doesn't activate Android keyboard (Google Chrome)"
- "I have updated my Cerbo GX firmware to v3.40~17. When using Gui-v2 in VRM I am not able to change the device name because no keyboard appears when I tap on the device name data input box. I am running VRM on Lenovo tablet, using android V10"

**Comment by DanielMcInnes** [comment]
If I connect to a cerbo directly via my phone, eg. browse to https://10.0.0.2/gui-beta/ , I can enter text ok.
![image](https://github.com/victronenergy/gui-v2/assets/6416318/3ce16e2c-4444-48b3-8d11-0749c07fae34)

If I connect to a cerbo via VRM on my phone, I see the issue, and when I click in a text entry field, no keyboard pops up.

**Comment by jpetrell** [comment]
Does not repro on iPad (and likely then also not on iPhone either), only on Android. This may be something VRM adds around the gui-v2 that Qt doesn't like, or a bug in Qt itself. Reading the source codes (commits [here](https://codereview.qt-project.org/c/qt/qtbase/+/260717) and [here](https://codereview.qt-project.org/c/qt/qtbase/+/295032)) looks like Qt creates an off-screen, hidden <input type=“text” contenteditable=true> element and gives it focus when a Qt input gains focus.

**Comment by jpetrell** [comment]
Fixed in the upcoming VRM website release, "the popup used for the remote console does not allow focusing on elements outside of it, therefore making the proxy input inaccessible".
