### ISSUE TITLE
After typing the virtual keyboard always comes up on a tap on Android (wasm)

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1154]
Open gui-v2 on the local network by pointing Android browser to [your_device_ip_address]/gui-beta. Open virtual keyboard by tapping any text field in gui-v2, e.g. one of the fields in Settings > Display & Languages > Minimum and maximum gauge ranges.

Virtual keyboard should open. Now close the keyboard. Then tap anywhere on the gui-v2 area.

Actual result: The keyboard reopens.

Expected result: The keyboard only reopens if you tap another text field.

When debugging with Chrome remote device debugger `chrome://inspect/#devices` I can see that initially `<body>` element is the active element (document.activeElement ). After focusing the text field a new `<input>` element becomes the active element, which it stays unless you reload the whole page.

https://github.com/victronenergy/gui-v2/assets/2203667/dd10ebac-08d1-40e9-ab97-7c172a2958a5

**Comment by jpetrell** [comment]
There are old [Qt issues](https://bugreports.qt.io/browse/QTBUG-88803) about Android keyboard always popping up, but such items are closed. Upgrading Qt might solve the issue, or we could work-around the issue by trying to set the `<input type=“text” contenteditable=true>` element contenteditable value to false whenever text field loses active focus inside the Qt window.

**Comment by chriadam** [comment]
Looks like the bug was closed by Qt even though the issue was never fixed.  I have pinged.

There might be some issue with Android Chromium also: https://issues.chromium.org/issues/40912131
