### ISSUE TITLE
Input field feedback: read-only not understandable

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#1166]
For most items it's not clear if they are enabled/disabled or readonly.

All fields are changeable now:

![Bildschirmfoto am 2024-05-30 um 11 55 32](https://github.com/victronenergy/gui-v2/assets/12592765/c1246277-a561-4b4e-b320-c92adb2f1719)

All fields are read-only now:

![Bildschirmfoto am 2024-05-30 um 11 58 06](https://github.com/victronenergy/gui-v2/assets/12592765/18aa0a1d-90bb-4df9-9d09-81723ab22546)

The only difference is, that an enabled button gets grayed.

**Comment by jpetrell** [comment]
With fixes made for #934 (that were just merged) the read-only text fields are now displayed as regular read-only text items:

![image](https://github.com/victronenergy/gui-v2/assets/2203667/1bd3702c-8a74-4933-8af4-16a0ff1aab5a)

**Comment by blammit** [comment]
Closing as fixed.
