### ISSUE TITLE
Input field feedback: no feedback for text fields

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#1167]
After entering a new value and pressing enter, there is no feedback, that this value was saved somehow. Would be nice, if the border turns green for some seconds or something like that.

This also because, if you do not press enter the value is not saved.

![venus-os-field-feedback](https://github.com/victronenergy/gui-v2/assets/12592765/555a33c1-c98b-4a1e-b4a3-2017e0031673)

**Comment by jpetrell** [comment]
Agree. Already filed as #1047, will close this as duplicate.

**Comment by mr-manuel** [comment]
I missed the other issue, thank you!
