### ISSUE TITLE
Display error when trying to open gui-v2 on the VRM website with VRM communication turned off

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1180]
Disable VRM two-way communication in VRM online portal settings. Access gui-v2 from the VRM website.

Actual result: Splash screen reports connecting to the backend, but the gui-v2 opens empty with no data displayed on any of the views.

Expected result: The user is instructed to go turn on VRM two-way communication either by the VRM website or by the gui-v2, and/or the two-way communication is always enabled so the situation cannot happen.

Could also warn the user if they try to toggle the VRM two-way communication switch to the off state.

**Comment by mpvader** [comment]
Solved
