### ISSUE TITLE
Auto selected BMS displaying empty value

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1193]
The automatically selected BMS is not displayed in GUI-v2, while it is displayed correctly in GUI-v1. Tested 3.40~21 GUI-v2. Reported on venus-tests. 

![image](https://github.com/victronenergy/gui-v2/assets/2203667/bcd2901d-93e9-4b7a-a94f-2ca8e8f010db)

**Comment by blammit** [comment]
On this system, the `/ActiveBmsService` and `/ActiveBmsInstance` are
valid, but the MQTT service referenced by this combination of service name and instance does not exist. It does exist on dbus, though. The issue could be related to the system using a virtual BMS.

Will check with @ReinvdZee on this one.

**Comment by jpetrell** [comment]
Doesn't seem common issue, lowering priority.

**Comment by ReinvdZee** [comment]
See [this](https://victrondevelopment.slack.com/archives/C020QG3JVEW/p1717726127695089) slack thread on the missing MQTT service. This will be merged in a coming release.

**Comment by blammit** [comment]
Closing as this will be fixed in VenusOS.
