### ISSUE TITLE
Battery details page showing empty values for Lynx parallel BMS

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1201]
Rein earlier commented that the battery details page on v2 lacked some values.

![image](https://github.com/victronenergy/gui-v2/assets/2203667/f731770b-2eaa-485a-8dff-9c509bab9c86)

**Comment by blammit** [comment]
Asked @ReinvdZee about this, he will provide details for reproducing this issue.

**Comment by blammit** [comment]
I think the bug here is that the detail page should not be available at all from the battery settings, since the only info available is the "available capacity".
