### ISSUE TITLE
Connected gensets UI changes

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1220]
We've done quite some changes to the UI of connected gensets on gui-v1. See [this](https://docs.google.com/document/d/1NohCfWdM3Aj-FIk6D3GXrWsDlFFxs05h/edit?usp=drive_link&ouid=113747478174641618706&rtpof=true&sd=true) doc. These changes should be implemented in Gui-v2 as well.

The new v1 UI looks like this: 
![genset_new_ui](https://github.com/victronenergy/gui-v2/assets/38864570/d2d33dce-b2df-448b-a163-f371d54606ce)

Manual start menu: 
![Screenshot from 2024-06-10 14-16-02](https://github.com/victronenergy/gui-v2/assets/38864570/6e06031b-045a-411a-a77f-f7804ea1bddb)

The v2 UI currently is: 
![image](https://github.com/victronenergy/gui-v2/assets/38864570/a4d9223a-e512-4deb-bb34-12f6297fd696)

**Alarms**
`dbus_generator` now contains two seperate alarms for monitoring the auto start/stop mode of the GX and of the genset. Both alarms can be enabled/disabled with **one** switch (already present in Gui-v2):
![image](https://github.com/victronenergy/gui-v2/assets/38864570/5e50cab2-cdf3-46d1-b500-b0779160ef38)
The alarms are issued by `dbus_generator` and published by `venus-platform`. As was already discussed [here](https://github.com/victronenergy/gui-v2/issues/1086) no UI changes are necessary for the alarms to show up in Gui-v2.

**Control Card**
The control card works properly as well:
![image](https://github.com/victronenergy/gui-v2/assets/38864570/fa623045-f17f-4c21-b193-461d1449aacb)

I can do a manual start and timed run and also enable/disable GX autostart from here. However, the state currently given in the manual start menu (embedded in autostart menu) can be out of sync with the state given in the card. But this is probably resolved if the UI changes are implemented. There are possibly some improvements to be made: 

- Display if the Genset's "remote start mode" is enabled or not. 
- Display the Genset / GX Auto start/stop state.

**Other issues**
The genset we're testing with also exposes a tank sensor. On gui-v1, this is picked up correctly. Gui-v2 shows the sensor but it is "unknown":
![image](https://github.com/victronenergy/gui-v2/assets/38864570/eda600bf-73f8-4071-9978-7249cc1fb927)
On the tanks overview it is displayed properly: 
![image](https://github.com/victronenergy/gui-v2/assets/38864570/2c6dc9e7-697f-4a2a-bad7-b145d53cd9f0)

Tasks:

- [ ] Remove the "Mode" option
- [ ] Move the autostart switch and manual start menu to the top-level
- [ ] Place status and error code of the GX and the genset on the top-level
- [ ] Add "Remote start mode" status beneath the phase information
- [ ] Modify the manual start menu to disable the menu items when the genset's remote start mode is disabled. Also display this text then: "The remote start functionality is disabled on the genset. The GX will not be able to start or stop the genset now. Enable it on the genset control panel"
- [ ] Look into the issue with the tank sensor

The menu is probably interleaved with the generator start/stop menu, be sure not to change the generator start/stop menu.

**Comment by chriadam** [comment]
This seems like a large number of UI changes / feature changes.  There were other similarly large changes (like the acsystem one) recently, also.  I am surprised that we are still receiving large feature changes at this point, considering the timeline.  I would ask: is this truly necessary for 1.0.0?

**Comment by blammit** [comment]
See [b9583fd7bee8f1120402ba4697693765c6f06f26](https://github.com/victronenergy/gui/commit/b9583fd7bee8f1120402ba4697693765c6f06f26) in gui-v1 for the main changes.

**Comment by chriadam** [comment]
Reopening issue.  Per testing on Tuesday:
1) settings -> device list -> DSE genset controller, the text "Error" should read "Control error code" so as to be distinct from "Genset error code" which comes later in the list.
2) Genset device is not showing up on Overview page as an AC Input (nor as a gauge on Brief page).  Simulation N.

**Comment by ReinvdZee** [comment]
Reported on slack: The generator manual start menu is not properly scaling. I reproduced this on a mobile phone. The controls work, but they do not scale evenly with the menu background. 

![image](https://github.com/victronenergy/gui-v2/assets/38864570/1da67354-4de0-4430-b627-e6b30bc43433)

**Comment by chriadam** [comment]
That latter issue (scaling of the dialog) is tracked separately by #1271

**Comment by blammit** [comment]
For reference, use [this](c0619ab66479) installation to test the "DSE genset controller".

**Comment by blammit** [comment]
> Genset device is not showing up on Overview page as an AC Input (nor as a gauge on Brief page). Simulation N.

This is because `com.victronenergy.system/Ac/ActiveIn/Source` is not set to a valid value, and gui-v2 relies on this to determine the current active AC input. (Also, `Ac/In/0/Connected` and `Ac/In/1/Connected` are not set.)

Normally `/Ac/ActiveIn/Source` is set, so I think this is a bug in the simulation. @ReinvdZee could you confirm whether this is the case?

**Comment by ReinvdZee** [comment]
@blammit `/Ac/ActiveIn/Source` is only set when there is a multi with an active input. Simulation N is only a recording of the genset, not of the vebus service, so if you run this on a system with no further devices, `/Ac/ActiveIn/Source` will indeed not be set correctly. 

You can use simulation O to test this. Simulation O also has a vebus system. I ran it and the generator widget showed up:

![image](https://github.com/victronenergy/gui-v2/assets/38864570/ee492e62-108e-42a2-bcaf-7e87958c45cb)

I would expect it to show up on the top-left instead of the bottom-left, though. But that may be a design choice. 



We may not even need a genset service to test this. I set AC input 1 to "generator" on the [lynx parallel test system](https://vrm.victronenergy.com/installation/402872/dashboard) and it shows up:
![image](https://github.com/victronenergy/gui-v2/assets/38864570/ac275876-4d8c-4e80-84da-6bc20cbfa1b2)

**Comment by blammit** [comment]
Note: I am currently clarifying with Rein how we should identify the active AC input, as it seems that /Ac/ActiveIn is only set when there is a multi device (like vebus) present. If this is the case, then some work is required to rearrange how the active AC input is determined.

**Comment by blammit** [comment]
Clarified this with Rein. gui-v2 can use `/Ac/ActiveIn/Source` for now. I will close this as all issues are resolved.
