### ISSUE TITLE
Deal with websocket URL on Venus giving a redirect for auth

### ISSUE THREAD

**Issue by wiebeytec** [victronenergy/gui-v2#1222]
With the new Venus security features, the websocket to MQTT on `https://venus.local/websocket-mqtt` may respond with a redirect instruction, header `Location: http://venus.local/auth/login.php?page=/websocket-mqtt`. This will cause the connection to fail, because the user needs to login in on that URL in the location header. For that, the GUI needs to exit and the page shown.

Can the GUI exit and follow the redirect?

One reason it will do this, is because the cookie can expire. That will be after a year. This is not really high priority because of that.

**Comment by jhofstee** [comment]
This is related to this issue https://github.com/victronenergy/gui-v2/issues/1254
