### ISSUE TITLE
Battery widget fails to display temperature on the Overview page

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1223]
Customer is [reporting](https://community.victronenergy.com/questions/292058/venus-os-v34026-available-for-testing.html?childToView=292862#answer-292862) that "My system no longer shows the battery temperature in the overview, although it is apparently available (see pictures). A reboot etc. did not bring any change. I can't say whether this is due to the recent change from the “normal” SmartShunt to the SmartShunt IP65 - I definitely didn't notice the absence before."

The same battery temperature is shown correctly in the settings.

![image](https://github.com/victronenergy/gui-v2/assets/2203667/e83ab630-8e75-431c-9e42-8877dc28dc9d)
![image](https://github.com/victronenergy/gui-v2/assets/2203667/38a15367-9fa8-4039-9b8c-0381c318a164)

**Comment by mr-manuel** [comment]
On my systems this works as expected. Maybe the customer has selected another battery monitor?

**Comment by blammit** [comment]
The overview widget shows the "system" battery from `/Dc/Battery/Temperature` so it's possible that is invalid for some reason.

**Comment by ReinvdZee** [comment]
Closed as it seems to be resolved on the user's system
