### ISSUE TITLE
List of batteries from overview drilldown is incomplete

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1224]
Clicking on the battery from the overview page shows a list of batteries in the system, if there is more than one battery.

The battery list is generated from `com.victronenergy.battery.*` but this is not sufficient. Some batteries are missing; see [this](https://victrondevelopment.slack.com/archives/C04RYU0UMDE/p1718001991024539) slack thread.

**Comment by blammit** [comment]
Marking as blocked; need more info about where to find a complete list.

**Comment by mpvader** [comment]
Hey @blammit, see showing all batteries chapter in UI document


(Still needs some input from Izak)

**Comment by blammit** [comment]
Note: the conclusion here was that the list of batteries should come from `com.victronenergy.system//Batteries`.
