### ISSUE TITLE
Provide breadcrumbs header for the settings pages

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1231]
GX devices have a lot of settings, sometimes in deep hierarchy. Replace the static settings page titles with a breadcrumbs pattern that visualises the user’s current location in the settings hierarchy, and makes it easy to jump to specific level in the parent hierarchy. See the Figma design for more details.

**Comment by DanielMcInnes** [comment]
from the figma, open the left side bar, click Views, Setting Redesign
