### ISSUE TITLE
Empty / invalid dbus service displayed on the device list

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1233]
Discovered when testing a genset on a GX with no other devices connected. 
Even though there is a dbus service for `vebus` with a lot of empty paths, GUI-v2 should not display it when it is not valid.
Gui-v1 does not display the invalid device in the device list. 

![image](https://github.com/victronenergy/gui-v2/assets/38864570/425083f2-3580-4e1f-90a9-196cc4679491)

This also leads to an empty control card: 
![image](https://github.com/victronenergy/gui-v2/assets/38864570/3888f4cc-a92d-4120-ba06-56eaaaea7295)

Issue appears on [this](https://vrm.victronenergy.com/installation/388348/dashboard) system. 
@blammit, @DanielMcInnes @chriadam You have access, and I will leave the system running

**Comment by blammit** [comment]
@ReinvdZee the Device List assumes that a device is valid if the /DeviceInstance is set, which is incorrect in this case. What would be a good test for validity? How about checking `/DeviceInstance`, `/ProductName` and `/ProductId` are all valid?

**Comment by ReinvdZee** [comment]
@blammit Gui-v1 finds a device valid if `/ProductName` or `/CustomName` is set. That is why in this case it works, because both are not set. However, I think V2 should use a more robust test for validity, so I agree with your suggestion:

**A device is valid if `/DeviceInstance`, `/ProductName` and `/ProductId` are all valid and set.** 

Keep in mind that `/CustomName` should be displayed when set, if not, then `/ProductName` is used.

**Comment by blammit** [comment]
Sounds good, thanks!

**Comment by blammit** [comment]
Discussed that /ProductId should not be mandatory. Just look for /DeviceInstance and /ProductName.

**Comment by chriadam** [comment]
Discussed with Rein that the isValid check is currently, wrong.  It is currently:
```
bool BaseDevice::isValid() const
{
	return !m_serviceUid.isEmpty() && !m_productName.isEmpty() && m_deviceInstance >= 0;
}
```

but it should be something like:
```
bool BaseDevice::isValid() const
{
	return !m_serviceUid.isEmpty() && (!m_productName.isEmpty() || !m_customName.isEmpty()) && m_deviceInstance >= 0;
}
```

**Comment by chriadam** [comment]
And, in the device list, if there is a custom name set, the custom name should be shown rather than the product name.

**Comment by blammit** [comment]
Okay, sounds like this previous conclusion was incorrect:

>  Discussed that /ProductId should not be mandatory. Just look for /DeviceInstance and /ProductName.

**Comment by blammit** [comment]
> And, in the device list, if there is a custom name set, the custom name should be shown rather than the product name.

Yep, this is how the name is generated in `components/Device.qml`.
