### ISSUE TITLE
The grid input overview page doesn't show any data when importing power

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1241]
Seen at "GRN - RS 3phase without EM"
On the overview page, the grid widget shows power being imported. When I click on the grid widget, PageAcIn is displayed, with all of the data fields empty.

![Screenshot from 2024-06-17 15-04-47](https://github.com/victronenergy/gui-v2/assets/6416318/8b3a1b78-4ce8-4461-8073-98fa943dc89a)

![Screenshot from 2024-06-17 15-04-42](https://github.com/victronenergy/gui-v2/assets/6416318/993d779f-95f2-4972-8c66-c49a3b2a8413)

![Screenshot from 2024-06-17 14-35-18](https://github.com/victronenergy/gui-v2/assets/6416318/22b4218d-1ef9-41b8-82cb-d6838d757f21)

**Comment by blammit** [comment]
I thought there was another issue like this, but I can't find it...

**Comment by blammit** [comment]
This is because the AC input on this system comes from a Multi RS system, not a grid or genset service, so showing the grid settings page in this case doesn't make sense. We could show PageMultiRs instead.
