### ISSUE TITLE
Cerbo GX Mk2 - Console on VE.Direct 1?

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1247]
On cerbo GX Mk2, Gui-v2 displays an option to enable the console on VE.Direct 1. The option does not work and I also don't think it should be there. AFAIK only the CCGX has a console on VE.Direct. V1 also does not display this option on the Cerbo GX Mk2.  

![image](https://github.com/victronenergy/gui-v2/assets/38864570/6d628165-03f5-49e5-849a-d62bb1f1b639)

If the option is supposed to be there, then it should at least be controllable. 
@mpvader

**Comment by mpvader** [comment]
Indeed, its a CCGX only option and does not need  to be implemented in gui-v2.

**Comment by chriadam** [comment]
Fixed.
