### ISSUE TITLE
Parent device page still shows the old name after renaming the device

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#1249]
Open device in Device list settings. Go to Device. Rename the device name. Go back one step. Then go back to device list page.

Expected result: The new name is shown.

Actual result: While device list settings listing shows the updated name, the parent device page after back-stepping initially still displays the old name.

**Comment by blammit** [comment]
Is this timing dependent? I couldn't reproduce it via wasm when renaming a solar charger or a battery.

**Comment by jpetrell** [comment]
> Is this timing dependent? I couldn't reproduce it via wasm when renaming a solar charger or a battery.

I can reproduce on battery. Here is a video demonstrating the issue using digital input:
https://github.com/victronenergy/gui-v2/assets/2203667/e7c2b932-b6c2-4fe4-9749-0642fdd998df

The respective list item on the Device list page updates, but the device setting page title doesn't update unless you reopen the page.

**Comment by blammit** [comment]
Oh sorry, I misunderstood. I thought you were referring to the item in the device page, rather than the page title.

**Comment by blammit** [comment]
Passing the name as a binding (instead of as a static value) from the Device List should fix this for the most part.
