### ISSUE TITLE
Overview page: Grid widget: confusion when some phases in watts and others in kilowatts

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1264]
![Screenshot from 2024-06-20 15-52-41](https://github.com/victronenergy/gui-v2/assets/6416318/ce22f66c-cfbf-4714-9304-c742150bea42)

In gui-v2, L1 should read '17 kW', not 17 W.
![Screenshot from 2024-06-20 15-52-46](https://github.com/victronenergy/gui-v2/assets/6416318/4e5b61fd-713b-4fbe-8258-980adb245cb8)

**Comment by blammit** [comment]
As [discussed](https://victrondevelopment.slack.com/archives/C04RYU0UMDE/p1702196841223049?thread_ts=1701519502.485569&cid=C04RYU0UMDE) with Matthijs, in this case the values should be adjusted to all use the same unit.

```
For three phase. I prefer all three numbers to use the same number of digits and be in thousands or not).

It should not be:
L1:         3W
L2: 12.1kW
L3:    100W

Instead it should be:
L1:    0.0kW
L2: 12.1kW
L3:    0.1kW
```
