### ISSUE TITLE
Console on VE.Direct should be CCGX-only option

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#1265]
1) Only the CCGX had UART on VE.Direct, so the "Console" setting under VE.Direct should be hidden on non-CCGX devices like Ekrano.
2) Attempting to enable the "Console" setting on a CCGX did not work.

**Comment by chriadam** [comment]
Marking as low priority, not for 1.0.0

**Comment by ReinvdZee** [comment]
Duplicate of https://github.com/victronenergy/gui-v2/issues/1247
