### ISSUE TITLE
Smart Shunt device issues

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#1267]
Was originally noted in the MultiRS issue, but it's unrelated to that:
1) settings -> device list -> smart shunt -> device -> "VE.Direct" text gets wrapped unnecessarily.
2) after disconnecting smart shunt the device is gone from device list rather than being cached in memory. (Is this really a bug? I guess, so, since it means the "Remove disconnected devices" button is useless if the device is always removed automatically?)

**Comment by chriadam** [comment]
The first issue is high priority and should be fixed for 1.0.0.

The second issue is medium priority and is not necessary for 1.0.0, I believe.

**Comment by ReinvdZee** [comment]
@chriadam Bullet 2 is an issue happening for all devices. Its [this](https://github.com/victronenergy/gui-v2/issues/1035) one.

**Comment by DanielMcInnes** [comment]
I can't reproduce this issue now - in the smart shunt device page, 'VE.Direct' is displayed correctly. Running v3.40~30

**Comment by DanielMcInnes** [comment]
@chriadam can I close this ticket?

**Comment by chriadam** [comment]
Did you try connecting to Rein's device where we saw this issue, via WebAssembly / VRM?

**Comment by DanielMcInnes** [comment]
yes, it's displaying correctly now.

**Comment by chriadam** [comment]
This scares me a bit.  Did we change anything to do with this, recently?

**Comment by ReinvdZee** [comment]
@chriadam @DanielMcInnes 

I can also not reproduce this issue right now. 
Yesterday, I've updated the system to V3.40~30, so it may be fixed now? 

I'll check some more devices with a VE.direct connected device today.

**Comment by DanielMcInnes** [comment]
@ReinvdZee , do you mind if I downgrade your system, check the issue, then upgrade again?

**Comment by ReinvdZee** [comment]
@DanielMcInnes 
>@ReinvdZee , do you mind if I downgrade your system, check the issue, then upgrade again?

Sure, go ahead. I'm not using it.

**Comment by DanielMcInnes** [comment]
Thanks @ReinvdZee . I couldn't reproduce with v3.40~29 either. Ugh.

**Comment by chriadam** [comment]
Removing high_prio label since we cannot reproduce the first issue. The second issue is low prio.

**Comment by chriadam** [comment]
Actually, closing, as the second issue is covered by #1035
