### ISSUE TITLE
Parallel Lynx BMS: Show that Lynx BMS is waiting to connect to a parallel system

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1269]
See [this](https://github.com/victronenergy/venus/issues/1283) issue, we'd like to show that a Lynx BMS is waiting to connect to the system. Currently, the BMS summary just shows its Soc, voltage and current (0A, because its not connected). 

Instead, the following should be displayed: 

-  ~~Summary (device list entry): "Waiting" + voltage delta + threshold (formatting suggestions welcome)~~
-  ~~BMS state: "Waiting"~~ 

~~**Paths**~~
~~When the BMS is in the waiting state, the path `/State` will be 18, which is a new state dedicated for this situation. 
The voltage delta can be calculated from the physical BMS voltage and the parallel BMS voltage:
Voltage delta = `com.victronenergy.battery.lynxparallelx/Dc/0/Voltage` - `com.victronenergy.battery.socketcan_.../Dc/0/Voltage`~~

~~And since its a delta, should we take the absolute value of it? @mpvader ?~~

~~The voltage threshold will be reported in the path `/ParallelConnectThreshold`, but this must be added to vecan, so the issue is currently blocked.~~

**UPDATE**

We've changed "Waiting" into "Pending" and made some more changes. See https://github.com/victronenergy/venus/issues/1283 and [slack](https://victrondevelopment.slack.com/archives/C0154KFUE1M/p1716554398290749) for the discussions. 

A new state with value 18 is added to the BMS to represent this state. The implementation must be as follows: 

When the path `/State` is 18:
- Set the "State" field to "Pending" 
- Set the summary field to "Pending <battery voltage> <soc>.
- Do **not** translate the "Pending" term on the summary. (Reason for this is to prevent overlap with the BMS name in case of long translations)
- Show the field "System voltage" in the device-page when `/State` is 18. This field contains the voltage of the parallel BMS. To find the parallel BMS the individual BMS is part of, use the `/N2kDeviceInstance` path to compose the parallel BMS service name: `com.victronenergy.battery.lynxparallel<n2kdevice instance>`. The path `/Dc/0/Voltage` gives the parallel BMS voltage. 

Gui-v1 screenshots:

![image](https://github.com/victronenergy/gui-v2/assets/38864570/ab523dc2-6c10-4512-bf81-3e6dd5decaca)
![image](https://github.com/victronenergy/gui-v2/assets/38864570/4db289e9-325c-4a15-975a-59c00a2ff21c)

**Comment by mpvader** [comment]
A delta? I thought we were going to show the absolute values.

**Comment by ReinvdZee** [comment]
>A delta? I thought we were going to show the absolute values.

In the meeting of 04-06, we decided to show the voltage delta + threshold on Gui-v2. On V1 we show the system voltage.

**Comment by ReinvdZee** [comment]
I've updated the original issue description and removed the blocked label. 

@blammit @chriadam @DanielMcInnes

**Comment by DanielMcInnes** [comment]
Hi @ReinvdZee , I'm having trouble debugging my issue with the replay files you sent me. The 2 BMSes don't show up for me in gui-v2, the data for them is not published over mqtt. I think it will be easier to debug this issue on the 'Lynx smart BMS  parallel -  test setup' we were using last week, with a BMS in 'Pending' state. (On that cerbo, the 2 BMSes do show up for me via mqtt).
