### ISSUE TITLE
AC Charger detailed data is off by one

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1270]
from: https://community.victronenergy.com/questions/292058/venus-os-v34026-available-for-testing.html

> AC Chargers are now also shown in the device list as of beta 29. I have a IP43 3 output 50 amp version and the battery data is shifted. Battery 1 shows voltage amps of real Battery 2, Battery 2 shows real Battery 3 and Battery 3 is empty. This is the case for GUI v2 on V1 all is still ok.

**Comment by ReinvdZee** [comment]
@chriadam @DanielMcInnes @blammit,

This is reproduced on [this](https://vrm.victronenergy.com/installation/2931/dashboard) system. 

The Skylla-i charger has 3 charge outputs, but they're off by one. 
![image](https://github.com/victronenergy/gui-v2/assets/38864570/cbabd610-168b-49a9-bcad-390b6567832e)
