### ISSUE TITLE
DVCC Max charge current setting modal layout issue

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1271]
User report:

![IMG_2067](https://github.com/victronenergy/gui-v2/assets/5200296/278dc691-1062-4cbc-9bc9-4f61bc1f5061)

on my phone, portrait:

![IMG_2065](https://github.com/victronenergy/gui-v2/assets/5200296/ce9f0ed5-36ac-440b-b208-d8c876872e92)

on my phone, landscape:

![IMG_2066](https://github.com/victronenergy/gui-v2/assets/5200296/f1b2d336-2b13-4111-b64a-b7e6569c4202)

**Comment by DanielMcInnes** [comment]
I can't immediately reproduce this issue. @mpvader , do we have access to this site?

**Comment by blammit** [comment]
I can reproduce it on my phone, and also in a desktop browser if I make the window smaller so that the amount of space available in the dialog shrinks.

**Comment by chriadam** [comment]
Yeah, we need to apply the same scaling to ModalDialogs that we apply to the root window.
