### ISSUE TITLE
Overview page: grid widget: decimals aren't shown for power values with kW scaling or higher

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1274]
If each phase is 9999kW, the value displayed is 10MW, not 9.999MW
![image](https://github.com/victronenergy/gui-v2/assets/6416318/0743d671-5495-4b32-8af0-d05b7b637bcd)
![image](https://github.com/victronenergy/gui-v2/assets/6416318/0743d671-5495-4b32-8af0-d05b7b637bcd)

**Comment by blammit** [comment]
Note:  for `W` values, this is the expected behavior, and there should be no decimals. However when the power is scaled to `kW`, `MW` etc. the decimal should be shown.

**Comment by ReinvdZee** [comment]
We document the number of decimals of units [here](https://docs.google.com/document/d/1yzHSpZoeZ0WOJJPhjivbhhD_iz37PaZtnZ9GpqVPh2M/edit#heading=h.82agtgjmtjv)

**Comment by chriadam** [comment]
Not sure this is a bug, as Joona specifically added a codepath to do this.  I recently expanded his code to make it more readable and maintainable, you can find that here: https://github.com/victronenergy/gui-v2/blob/main/src/units.cpp#L332

Basically, the precision is clipped to zero if we are using a scaled-up unit and the value is high enough.  It also does some anti-hysteresis stuff to ensure that it doesn't cycle between 10MW and 9.999 MW over and over, etc.

**Comment by DanielMcInnes** [comment]
I don't think this is a bug either, closing the issue
