### ISSUE TITLE
Keyboard input not working in WebAssembly builds with Chromium browser on Linux

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#1279]
Jeroen noticed a problem with keyboard input on Chromium in password fields (e.g. general / security profile -> password).
From some limited testing, we believe it works in Firefox on Linux, and in Chrome on Windows, and Safari on Mac OS X.  But not in Chromium on Linux.
Will investigate - one possibility is to update to later version of Qt WebAssembly if this has wider support.

**Comment by DanielMcInnes** [comment]
FYI, I cannot reproduce this issue (Chromium on ubuntu 22.04) on my system

**Comment by blammit** [comment]
@jhofstee will reopen if he can reproduce again.
