### ISSUE TITLE
Display off timer setting does not work

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1290]
Should be able to set the display off timer from Settings > Display.

**Comment by blammit** [comment]
Looks like `screenblanker.cpp` should respond to changes to `/Settings/Gui/DisplayOff` from the UI, just as `screensaver.cpp` does in gui-v1.

**Comment by blammit** [comment]
Note: when implementing this, also hide the "Display off timer" setting on wasm builds. We already do this for adaptive brightness and brightness settings.

**Comment by blammit** [comment]
Can't reproduce this issue, waiting for further information.

**Comment by blammit** [comment]
Reported issue was that the timer options wouldn't work, and the displayed stayed on regardless.

**Comment by DanielMcInnes** [comment]
I just changed the timer to 10 seconds on a wasm build, and after 10 seconds, my cerbo screen turned off. Cannot reproduce. I have made changes to hide the 'Display off timer' in wasm builds.
