### ISSUE TITLE
Solar Yield drilldown page from overview should display Error Number as well as Error String

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#1303]
ESS Demo, Overview Page, Solar Yield drilldown, Error list entry should display number (#0) as well as string ("None").

**Comment by chriadam** [comment]
When changed from 0 to 1 via dbus-spy, the number displays as red, but there is no description.

**Comment by chriadam** [comment]
Same issue applies to the MPPT (PV Charger) drilldown.  Error code isn't shown, or description isn't showing.

**Comment by blammit** [comment]
@chriadam This appears to be working fine for PV chargers, or at least on [this](https://vrm.victronenergy.com/installation/183123/dashboard) if I go to Overview > Solar drilldown > Some PV charger > Alarms and Errors, I see this:

![image](https://github.com/user-attachments/assets/64437cd2-f844-4b56-8c8f-fe9c91d86303)

**Comment by blammit** [comment]
@jepefe @ReinvdZee can [charger_error from veutil](https://github.com/victronenergy/veutil/blob/master/inc/veutil/qt/charger_error.hpp) be used to translate PV Inverter error codes into text descriptions? In [charger_error.cpp](https://github.com/victronenergy/veutil/blob/master/src/qt/charger_error.cpp) I can see some inverter-specific errors like `CHARGER_ERROR_INVERTER_OVERLOAD = "Inverter overload"`, but just want to double check.
