### ISSUE TITLE
WASM build: MQTT on LAN switches - lockout possible

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#1309]
It now happened to me, that I accidentially clicked on the `MQTT on LAN (SSL)` entry under Settings -> Services in the WASM build. This locked me out and I had to switch to the GUIv1 to turn it on again. If there is only GUIv2 in the future such a click would lock you out without the possibility to get back in, if you do not have SSH access, VRM enabled or a display connected.

I think disabling `MQTT on LAN (SSL)` and `MQTT on LAN (Plaintext)` should not be possible, if currently needed for the GUIv2 to connect.

**Comment by mpvader** [comment]
All this will change soon in the security build
