### ISSUE TITLE
Lynx Shunt VE.Can peukert exponent not adjustable

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/gui-v2#1323]
Reported on community:
https://community.victronenergy.com/questions/292058/venus-os-v34026-available-for-testing.html?childToView=308265#answer-308265

I was able to reproduce this on a temporary test system. Unfortunately, the other test system is in pieces, but I will try to setup another one asap. At first glance there is nothing obvious to see [here](https://github.com/victronenergy/gui/blob/f96aa4c070e422fc85bf41829f82af265ac0e3c4/qml/PageBatterySettingsBattery.qml#L81) and no difference compared with [gui-v1](https://github.com/victronenergy/gui/blob/f96aa4c070e422fc85bf41829f82af265ac0e3c4/qml/PageBatterySettingsBattery.qml#L81).

Gui-v1 shows the correct data, gui-v2 doesn't:
![image](https://github.com/user-attachments/assets/0732618b-911f-4d36-9972-9bdadbe527a4)

MQTT explorer also shows the correct data:
![image](https://github.com/user-attachments/assets/9b97e310-5975-45d8-b215-fb3e2e6ee670)

Gui-v2 also does not allow changing the settings, the +/- buttons are disabled, so it seems.
![image](https://github.com/user-attachments/assets/42e02e4c-965d-4c47-9cc1-224a9852e690)

**Comment by blammit** [comment]
I can reproduce this locally if I add:

```
"/Settings/Battery/PeukertExponent": 1.03999999,
```

to the lynx battery settings in mock mode.

@DanielMcInnes do you want to look into this? I think it's an issue with the precision handling/input for the ListSpinBox, or maybe the step size, and I know you were fixing some issues there before.

FYI the "Peukert exponent" is available under: battery page > Settings > Battery bank.
