### ISSUE TITLE
L2 shows dashes while L1 and L3 don't

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1326]
On [this system](https://vrm.victronenergy.com/installation/370388/overview), which is a EM24 energy meter, three phase, plus a single RS on L3, gui-v2 shows -- on L2 while there is data for it.

Note that the system shows dashes for both L1 and L2 in case of a grid outage, which happens often there.

Discussion with user of that system: https://victrondevelopment.slack.com/archives/C04RYU0UMDE/p1717966505212219

I'm assuming this is a small typo or bug, hence v1.0.0 milestone. If it gets all complicated then we can move this to a later milestone.

![image](https://github.com/user-attachments/assets/ef2da900-d5a9-4397-9888-f9e722ee27ea)

**Comment by DanielMcInnes** [comment]
Hi @mpvader , I don't have access to this installation, could you add victron.vrm@qinetic.com.au please?
