### ISSUE TITLE
Key combinations to gain superuser or service access don't work without keyboard

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#1333]
On CerboGX device, would be good to have a way to gain superuser access in PageSettingsGeneral.qml without needing to get the VKB to show somehow.  E.g.: maybe just touching some UI element 5 times in a row, should trigger it?

**Comment by mr-manuel** [comment]
Even, if I'm able to pop the VKB out, there are no arrows on the VKB when using touch devices, like Cerbo GX Touch or Ekrano GX.

Maybe 5 taps on `User & installer` under `Access level`, if that access level is already enabled could be an option.

**Comment by blammit** [comment]
In PageSettingsGeneral, if you drag the list down from the starting position and hold for 5 seconds, and the current user level is User+Installer, then it will change to Superuser. (This is the same as the behavior in gui-v1.) Is this sufficient?

**Comment by blammit** [comment]
@chriadam ^ is that sufficient? Can this be closed?

**Comment by chriadam** [comment]
Ah, great.  I guess this doesn't apply for service usage, but yes so long as superuser is accessible this way, let's close the issue as invalid.
