### ISSUE TITLE
Set root password

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#1334]
When I try to set the root password, I get the message "not yet implemented".

**Comment by mr-manuel** [comment]
Seems to work with the Venus OS `security8` release and GUIv2 `v0.3.5`, but not with Venus OS `v3.40~39` and GUIv2 `v0.3.6`.

## Venus OS `security8` release and GUIv2 `v0.3.5`
![grafik](https://github.com/user-attachments/assets/7c14fe77-31c1-4f27-9ff2-f21159936c5f)

## Venus OS `v3.40~39` and GUIv2 `v0.3.6`
![grafik](https://github.com/user-attachments/assets/3fe8d725-32e2-4370-8c20-7d3e43200210)

**Comment by mpvader** [comment]
Hey @mr-manuel 

This is intended to only work with the security branches.

and thus not yet plain v3.40~39

**Comment by mpvader** [comment]
Duplicate with #1384
