### ISSUE TITLE
When a battery is created with an invalid serviceUid, it is never destroyed

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1340]
`mqtt/system/0/Batteries` is updated regularly, perhaps when voltage / current changes? If  the reported batteries are not already part of the model, new Battery objects are created, and are then only added to the model when they become valid, which never happens in some situations. A few seconds later, `mqtt/system/0/Batteries` is updated again, and more invalid Battery objects are created.

**Comment by DanielMcInnes** [comment]
I have only seen this happen on a simulated system, that reported batteries via mqtt/system/0/Batteries that didn't exist. However, if it did happen on a real system, it would be tricky to track down. I think gui-v2 should be able to cope with something like this without leaking.

**Comment by blammit** [comment]
Real devices are unlikely to have an invalid service uid, so setting this to low priority.

**Comment by blammit** [comment]
@DanielMcInnes  With the changes for https://github.com/victronenergy/gui-v2/issues/1357, all Battery objects generated from `mqtt/system/0/Batteries` are now deleted when when the Battery drilldown page is popped. I think this is sufficient to ensure they are cleaned up; is this okay?

**Comment by DanielMcInnes** [comment]
@blammit , not really. We could be on any page, and every time battery current changes (I saw this happen about every 2 seconds) we create new battery objects. If they never become 'valid', they leak

**Comment by blammit** [comment]
They shouldn't be created anywhere except the Battery list page now. This is a change from before, when they were created as part of the `Global.batteries.model` generation.

**Comment by DanielMcInnes** [comment]
oh right, that should be ok then
