### ISSUE TITLE
RS control pane

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1342]
when accessing the on/off/charger-only for the RS, I encountered below pop-up.

Should Close be renamed to Cancel?

![image](https://github.com/user-attachments/assets/11a328dc-a35a-4aa5-9981-6f0e7bf55623)

**Comment by DanielMcInnes** [comment]
I think 'Cancel' would be better than 'Close', as it's more like what Windows does, and people are used to it. I personally would prefer to change 'Set' to 'OK' for the same reasons, but I don't know how everybody else feels about that.

**Comment by DanielMcInnes** [comment]
@mpvader , re. "Should Close be renamed to Cancel?", it is unclear to me whether you want 'Close' renamed to 'Cancel', or you just want feedback.

**Comment by mpvader** [comment]
Hey @DanielMcInnes , I wasn’t sure; but yes please change Close to Cancel.

Set / OK is perhaps a bit less trivial - I don’t know. Anyway lets leave that as is.

**Comment by DanielMcInnes** [comment]
@mpvader , do you just want it changed for this specific dialog, or for all dialogs that have 'Close' and 'Set' buttons (there are many)? I will make a list of affected dialogs if you want.
