### ISSUE TITLE
VRM read-only mode needs to be supported in gui-v2

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#1351]
From Wiebe: read-only mode has been added to VRM.

If it is read-only, you will get `N/portal_id/settings/0/Settings/Network/VrmPortal {"max":2,"min":0,"value":1}` (I assume value 2 would mean read/write, 1 means read-only, and 0 means no-access? not sure though).

In the case where the client is connected to a read-only VRM portal, the UI should show to the user that it is in read-only mode (perhaps in the title bar?), and disable / grey-out all of the settings controls.

**Comment by mpvader** [comment]
duplicate: https://github.com/victronenergy/gui-v2/issues/560
