### ISSUE TITLE
Device List should show all batteries under com.victronenergy.battery.*

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1357]
https://github.com/victronenergy/gui-v2/issues/1224 changed the battery list to be generated by `com.victronenergy.system/Batteries` instead of `com.victronenergy.battery.*`. However, this affects the batteries shown in the Device List as well. 

We actually need two separate battery lists, like this:

- When clicking on the Overview battery, show a list of all batteries in com.victronenergy.system/Batteries (if there is more than one)
- In the Device List, show all battery services under com.victronenergy.battery.*

**Comment by mpvader** [comment]
hey @blammit , this is one high prio rather than medium; since the data/menus of those batteries are now effectively no longer reachable unless worked around by setting things up in settings -> system -> battery measurements.

**Comment by blammit** [comment]
Can be tested on [this](https://vrm.victronenergy.com/installation/133622/dashboard) installation. There are three com.victronenergy.battery.* services, but only one battery in the `com.victronenergy.system/Batteries` list. So, the Device List should show the three batteries, but only one should be accessible via the Overview Battery drilldown.

**Comment by blammit** [comment]
@mpvader  I noticed on [this](https://vrm.victronenergy.com/installation/366384/dashboard ) installation that `com.victronenergy.system/Batteries` may include `genset` services. In this case, would you expect the battery drilldown list to show the details that are typically shown for genset services, like this:

<img width="811" alt="image" src="https://github.com/user-attachments/assets/9f3c2a15-a2cc-4561-bb90-714a68173bf1">

Because the problem is, at the moment, the battery drilldown list tries to show the battery details like `/Soc`, `/Dc/0/Voltage` etc. but that is not present for genset services, so it looks like this in the drilldown list:

<img width="811" alt="image" src="https://github.com/user-attachments/assets/f642b9e8-ceec-41fd-93a6-11837294b672">
