### ISSUE TITLE
Add critical loads to gui-v2

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1361]
Nice to have for v1.0.0 - but non-blocking since wrt design not trivial.

Test systems (all with energy meter ofcourse):
- Multi RS three phase: [Groningen - RS3phase with EM](https://vrm.victronenergy.com/installation/394636/overview) - this is a non-critical test system in Groningen, update Venus OS when you need to.
- VE.Bus Multi three phase: [system of Warwick - don’t mess up!](https://vrm.victronenergy.com/installation/149250/overview)

The right side of the screen can now show up to three boxes:
- Loads
- EVCS (one widget for all of them.
- DC loads

Some options:
- add a fourth box, if that fits
- add it into the AC Loads box, and show both side by side, perhaps uses less space.

Note that more is coming, seeing heatpump for example. (cc @philipptrenz )

And note that EVCS can be either part of the non-critical AC loads circuit, or on the critical AC loads circuit. And is also configured as such.

And also note that there is ongoing discussion wrt what the right wording is. Should we introduce "non-critical loads" as term? (I'm not convinced that we should), and what about essential loads, etc etc.

Wrt getting the data, that is easy, since its on D-Bus already.

Screenshots:

![image](https://github.com/user-attachments/assets/215973bb-7f70-4bc6-b1c8-948df07dff20)

Screenshot showing all boxes:

![image](https://github.com/user-attachments/assets/f7bb0f54-eb5e-4bd5-8793-c3948f398b3a)

**Comment by jepefe** [comment]
Discussed with Serj, he is working on this.

**Comment by blammit** [comment]
Serj has provided the design, this is ready for implementation.

**Comment by blammit** [comment]
https://github.com/victronenergy/gui-v2/pull/1489
