### ISSUE TITLE
'Access Level' radio buttons allow selecting multiple access levels at the same time

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1373]
I have 'Service' access level, and when I try to set the access level back to 'user' or 'installer', I can have multiple radio buttons selected at the same time
![Screenshot from 2024-07-26 10-59-54](https://github.com/user-attachments/assets/4611bec9-3834-417f-8e05-72dc6bca6565)

**Comment by DanielMcInnes** [comment]
Yes it is. I didn't realise the behaviour was different when clicking the list item. For some reason, I always click the button part, rather than the list item part.

**Comment by blammit** [comment]
Great, good to know. I'll verify this as part of those changes.

**Comment by blammit** [comment]
https://github.com/victronenergy/gui-v2/pull/980 has been merged, verified this is okay now. Closing.
