### ISSUE TITLE
Device list: Devices are shown multiple times

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/gui-v2#1376]
See conversation on slack: https://victrondevelopment.slack.com/archives/C020QG3JVEW/p1721908495869879

**Comment by blammit** [comment]
Reproducible on [this](https://vrm.victronenergy.com/installation/366384/dashboard) installation.

The genset controller is displayed multiple times:

<img width="1012" alt="image" src="https://github.com/user-attachments/assets/1c117c0b-04a3-4060-b51c-dca69e23a701">

**Comment by blammit** [comment]
This will be fixed by the changes for https://github.com/victronenergy/gui-v2/issues/1357.

**Comment by blammit** [comment]
#1357 has been merged; closing this one.
