### ISSUE TITLE
Generator drilldown on WASM doesn't work

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1405]
On Venus OS 3.50~14. 
The WASM correctly shows the blue outline on the generator widget:
![image](https://github.com/user-attachments/assets/8dfca5f1-adde-4fa6-8e83-d1d022d1ae7c)

But the drilldown does not work. It opens an empty page. Locally, this works properly. 
This is on a system with a vebus system connected, if that matters. This can be tested with the DSE simulation on venus-docker.

@blammit
I suppose we need to publish the instance number of the main generator? 
As indicated by @izak's comment [here](https://github.com/victronenergy/vrm-portal/issues/314#issuecomment-1980630339) (issue needs to be reopened when this is fixed) this may also be useful for VRM.

**Comment by blammit** [comment]
Hm, I'm not sure what's going on here. I tried connecting to [this](https://vrm.victronenergy.com/installation/366384/overview) installation, which does have a DSE genset, and I was able to open the generator drilldown there.

> I suppose we need to publish the instance number of the main generator?

The drilldown page shows `PageAcIn.qml` for the genset that is being shown, so it shouldn't be necessary to get an instance number separately.

**Comment by ReinvdZee** [comment]
@blammit,

I'm testing on [this](https://vrm.victronenergy.com/installation/402872/dashboard) system. It works properly with the DSE genset simulator of venus-docker. 

However, when I connect the system to the physical genset controller, it behaves as I described in my first comment. Small demonstration:

[Screencast from 13-08-24 13:45:06.webm](https://github.com/user-attachments/assets/9bebd7ea-aaf9-4c2a-915c-005a4af76c7a)

If I open gui-beta on VRM, it works properly, though. The GX is running Venus os 3.50~14.

You can test it on the system. Be careful not to start the generator, its connected to a physical genset controller.

**Comment by blammit** [comment]
Note: discussed with @ReinvdZee that this can't be reproduced now. Will have to check again further down the track.

**Comment by mpvader** [comment]
Is this bug still reproducible @ReinvdZee

**Comment by ReinvdZee** [comment]
@mpvader,
Tested on the [ESS system](https://vrm.victronenergy.com/installation/473156/dashboard) with 3.50~42.

There actually is no drilldown anymore:
![image](https://github.com/user-attachments/assets/a1ba4328-ba83-4a13-8da9-3aa6d73a8623)

The generator is there and AC input 1 is configured as "Generator".
Same behavior is on [this](https://vrm.victronenergy.com/installation/366384/overview) system (see @blammit's [comment](https://github.com/victronenergy/gui-v2/issues/1405#issuecomment-2277192139))

**Comment by blammit** [comment]
Thanks, will look into this.
