### ISSUE TITLE
Changing user role to 'User' or 'User & Installer' doesn't work anymore

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1408]
Tested on Venus OS v3.50~14. When attempting to set the access level to 'User' or 'User & Installer', the password input box disappear and the desired user level is not selected: 

[Screencast from 12-08-24 14:55:01.webm](https://github.com/user-attachments/assets/79f576f7-bda1-43d8-9e9f-925f7403f7b9)

This happens when transitioning from any access level to 'User' or 'User & Installer'.

**Comment by mr-manuel** [comment]
Should be fixed with https://github.com/victronenergy/gui-v2/pull/1402

In the meanwhile you can still enter the password and hit enter.

**Comment by ReinvdZee** [comment]
Oh alright, already fixed. 
Thanks, I'm closing this one.

**Comment by blammit** [comment]
Not yet fixed -- I'll reopen and mention this in the commit in #1402, then this can be closed automatically when that PR is merged.
