### ISSUE TITLE
Genset page: service & runtime metrics

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1409]
Some work is done related to run time and service metrics (see [issue](https://github.com/victronenergy/venus/issues/1315)). Following changes apply to the connected genset menu, as well as the relay-controlled (generator start/stop) menu, unless otherwise noted.  

- [x] Remove “Operating time” of connected gensets from the “Engine” page.
- [x] Move the “Run time and service” from settings to the top-level and add some items. This menu should contain:
a. Total run time. This field is synchronized with `/Engine/OperatingHours` (if valid). If the path does not exist (relay controlled generator) or is invalid (unsupported by connected genset), the total run time entry should be modifiable like it is now.
b. Daily run time counters (submenu)
c. Daily run time counters reset button
d. Time to next test run (if enabled)
e. Service timer (if nonzero service interval)
f. Service interval setting
g. Service timer reset button
- [x] Rename “Run time” to “Current run time” and show it on the top-level if the generator is running, warming up or cooling down. (`/State` equal to 1, 2 or 3).
- [x] Reorder the menu structure of the generator start/stop (relay) to be the same as that of the genset menu.

The new run time & service menu:
![image](https://github.com/user-attachments/assets/167f4880-f68e-452d-958d-0c43d64922c6)
![image](https://github.com/user-attachments/assets/e76d8831-dc24-4a5d-b67d-f633d84f1789)

**Comment by ReinvdZee** [comment]
The new "Run time and service" menu looks like this:
![image](https://github.com/user-attachments/assets/a8d70032-0e17-49d6-846a-005207751de9)

I also moved the "Accumulated running time since last test run" entry here. It is only visible when test runs are enabled and the user has access level service.

**Comment by mpvader** [comment]
discussed today in the meeting @blammit will look into this herself, with help from Philipp, if she gets to this one before Rein is back.

**Comment by blammit** [comment]
@ReinvdZee I've made a PR at https://github.com/victronenergy/gui-v2/pull/1448 using the patch you sent me earlier. I added some checks for empty UIDs, as we discussed previously.
