### ISSUE TITLE
Improve history menu / day selection dropdown for VE.CAN connected MPPTs

### ISSUE THREAD

**Issue by ThiemoVanEngelen** [victronenergy/gui-v2#1428]
CAN connected MPPTs do not have the 30 day history on the dbus. The History screen however still shows "Today", "Yesterday", "Last 7 days", "Last 14 days" and "Last 30 days". The info shown for "Last 7 days", "Last 14 days" and "Last 30 days" is however all the same, as these MPPTs only have a 2 day history. Also, the data in the "Last N days" screen most of the time will look a lot like "Yesterday", especially at the beginning of a new day. This can lead to confusion, at least for some users ([example](https://victron.discourse.group/t/v3-50-13-guiv2-mppt-history-incomplete/1056/1)).

The dbus contains a daysAvailable item. Perhaps when daysAvailable is 2, a different option can be shown like "Today + Yesterday" or "Last 2 days"?

**Comment by blammit** [comment]
Makes sense, thanks - adding to 1.0.0.
