### ISSUE TITLE
Improve Generator card display of running state and runtime

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1432]
The current generator card looks like this:

![image](https://github.com/user-attachments/assets/9d6be340-831f-4d3b-85c6-2852f753d468)

There are two issues here:

- The "Running by SOC condition" text is longer than what's desired in the design
- The runtime should be clear about whether it's showing hours-minutes or minutes-seconds. When under a minute, it's clear that it's seconds because the number will change every second, but the UI should be more explicit about this.

Updated design from Serj is like this:

![image](https://github.com/user-attachments/assets/05c5c33f-52a6-4468-86a5-af35e7e5e234)
![image](https://github.com/user-attachments/assets/8929824d-4d53-473e-84dd-2213429bb2a8)

So the tasks to be done are:

- [x] Update the generator card to show the generator state and condition, separated by a dot if necessary. If it was auto-started (i.e. any start condition other than "Manual start" or "Test run") then show "Auto-started" as the state text.
- [x] Update the runtime format in the generator card: show a "s" suffix when the runtime is less than a minute, otherwise show the "hh:mm" format without a suffix.
- [x] Similarly update the runtime format in the generator start/stop dialog. (This is the dialog that is shown when "manual stop" is pressed.)

**Comment by DanielMcInnes** [comment]
@blammit do you have a link to Serj's updated design for this?

**Comment by blammit** [comment]
@DanielMcInnes that wasn't specified, but I believe the text should be "Manually started" in that case.
