### ISSUE TITLE
add setting to hide input loads on overview

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1460]
as per gui-v1 commit 7cecfbf09dd5899bca7a9c76fd16ed12ee55f332

**Comment by DanielMcInnes** [comment]
This is to be used in systems with AC-coupled PV on the input,
    or systems with a grid meter used for energy accounting, but
    with no actual loads on the input side. It hides the AC input
    side loads on the overview.
    
    https://github.com/victronenergy/venus/issues/1328

**Comment by blammit** [comment]
Done as part of https://github.com/victronenergy/gui-v2/pull/1489

**Comment by blammit** [comment]
Actually no, this is a separate task. Re-opening.
