### ISSUE TITLE
hide input loads if system does not have any

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1461]
As per gui-v1 commit eab6fd439c2a9fc0957ce7e31039603741e1871b

    A new feature, introduced in systemcalc, allows for a system with a
    grid meter, but no loads between the grid meter and the
    inverter/charger. This is typical in systems where a grid meter is
    installed only to obtain vector registration for energy counting.

**Comment by blammit** [comment]
Done as part of https://github.com/victronenergy/gui-v2/pull/1489
