### ISSUE TITLE
add Node-RED submenu with factory reset

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1462]
as per gui-v1 commit [c2f0e33d3da7abc0b865f9125f542291a722ded1
](https://github.com/victronenergy/gui/commit/c2f0e33d3da7abc0b865f9125f542291a722ded1)

    Adds option to reset node-red from the user interface.
    User is asked for confirmation before the reset.

**Comment by mpvader** [comment]
To test, set the Image type (in the settings -> firmware menu) to Large, and then update.

and otherwise Rein can help to explain as usual

**Comment by chriadam** [comment]
Fixed
