### ISSUE TITLE
add missing check for VNC on VRM, VNC should be enabled as well

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1468]
as per gui-v1 commit 752a6ea3afd34fafc32a3e89cf59485b5bf2b469

**Comment by chriadam** [comment]
I think this is related to Remote Console on VRM, which is a gui-v1 specific thing.  I don't think we have any Remote Console specific settings in gui-v2.

**Comment by chriadam** [comment]
See #1490
