### ISSUE TITLE
add an explanation why Remote Console on VRM is turned off

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1470]
as per gui-v1 commit dc821221e131af5a64049e4289b2f588b884ec2d

    add an explanation why Remote Console on VRM is turned off
    
    These submenus must actually be regrouped / some better status page
    should be created.

**Comment by chriadam** [comment]
This is a Remote Console specific setting, which is gui-v1 specific.  We don't have this settings page in gui-v2.  See #1490
