### ISSUE TITLE
improve deciding to use grid parallel overview

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1478]
as per gui-v1 commit 8794e5aed69dbeeb3b3dae246bbac4b39d7a5fdb

    improve deciding to use grid parallel overview
    
    In the past, OverviewGridParallel was used for any system with
    type Hub-4 or ESS. With the addition of other hardware with the
    same capabilities, a better way is needed.
    
    Additionally, there are some systems that have a grid meter but
    are not configured as an ESS system. In such systems we still
    want to see an overview of what the entire system is doing,
    so we still want to show the GridParallel overview.
    
    Therefore, if the Grid is measured by a grid meter, switch to
    the GridParallel overview instead of using the system type.
    
    This also makes Multi-RS display properly.

**Comment by blammit** [comment]
In gui-v2 there is only one Overview page, so it doesn't need to update any logic in regards to choosing the correct Overview page.
