### ISSUE TITLE
Reconnect does not work

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#1480]
When you have opened the WASM build and reboot the GX device, the GUI does not reconnect and the page need to be refreshed.

In the developer console of the browser you see that two retries are made and after an error is thrown.

```
BackendConnection state: Victron::VenusOS::BackendConnection::Reconnecting (2) venus-gui-v2.js:8:18090
Firefox cannot establish a connecton to the server at ws://venus.local/websocket-mqtt. venus-gui-v2.js:8:243746
```

![Bildschirmfoto am 2024-09-17 um 11 01 00](https://github.com/user-attachments/assets/d342b242-c5d7-400f-afbb-5909e3d51e65)

**Comment by chriadam** [comment]
Fixed.  Please let me know if you still see this issue when using v0.3.12.

**Comment by mr-manuel** [comment]
Can confirm that this is fixed.
