### ISSUE TITLE
Use venus-platform for backlight handling

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1483]
there are minor logic differences to be applied

as per gui-v1 commit 5f81c62df8bc27e0506a2a363cbfcd3c643f8696

**Comment by chriadam** [comment]
We already use systemsettings /Settings/Gui/AutoBrightness and /Settings/Gui/Brightness etc values.
So, what do we need to change in gui-v2?  Is it just: `hasAutoBrightness: isValid && max === 1` ?

**Comment by DanielMcInnes** [comment]
> We already use systemsettings /Settings/Gui/AutoBrightness and /Settings/Gui/Brightness etc values. So, what do we need to change in gui-v2? Is it just: `hasAutoBrightness: isValid && max === 1` ?

yes, that's right
