### ISSUE TITLE
Test that gui-v2 has the mk3 firmware update feature and that it works

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1495]

**Comment by vejpasop** [comment]
MK3 firmware update works as expected
![image](https://github.com/user-attachments/assets/04b294bf-fb26-4800-bbac-55852bc3aa08)
![image](https://github.com/user-attachments/assets/e68a83dc-51f0-4a49-b69d-15b7a81683a2)
![image](https://github.com/user-attachments/assets/fa1bfa04-cafe-46c8-925a-8caaea9340e1)
![image](https://github.com/user-attachments/assets/1a6c7a5d-d8f9-4a76-9aa7-9864016b0795)
