### ISSUE TITLE
Add configurable "start page" 

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1496]
Allow a "start page" to be configured. This is the page that will be shown:

- on application start-up
- after the application is idle for a certain time, as configured in settings

Add a settings page at Settings > Display & Language > Start Page, with these options:

- Start page 
   Show this page on application start-up.
    - Auto (toggle)
    - Brief
    - Brief - side panel open
    - Overview
    - Levels - Tanks
    - Levels - Environment
    - Battery overview
    
- Timeout
  Revert to the start page when the application is inactive.
    - Never  <-- this is the default selection
    - 1 minute
    - 5 minutes
    - 10 minutes
    - 30 minutes
    - 60 minutes

**Comment by blammit** [comment]
Added "blocked" label, pending some settings to store these values, e.g. `/Settings/Gui/StartPage` and `/Settings/Gui/StartPageTimeout`.

**Comment by jhofstee** [comment]
I added them as /Settings/Gui2/StartPage /Settings/Gui2/StartPageTimeout so that it is clear they belong to gui-v2 only.

**Comment by blammit** [comment]
Thanks! Removing blocker tag.

**Comment by blammit** [comment]
Thanks, removing blocked status.

**Comment by blammit** [comment]
> Start page
> Show this page on application start-up.
>
> Auto <-- this is the default selection
> After one minute of inactivity, if the current page is one of the following, then save it as the start page.

Actually, the "auto" option should be a separate toggle, not an extra option in the list. Otherwise, using the "auto" feature means that a page would become the start page automatically, but then it will not change again after that (unless the user goes to the settings to change it), which would be confusing. Will update the task.
