### ISSUE TITLE
Hide invalid motordrive items

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/gui-v2#1510]
Depending on wether the "Motordrive" service is provided by a 3rd party motor integration or a SmartShunt, some parts may not be available. I updated the [dbus motordrive service specification](https://github.com/victronenergy/venus/wiki/dbus#motordrive), please hide all optional paths in case they are invalid.

![192 168 254 90_gui-beta_(Ekrano GX) (20)](https://github.com/user-attachments/assets/41e16ead-332a-4f00-a7eb-d807e976a63c)

**Comment by blammit** [comment]
@philipptrenz can all paths be hidden if they are invalid? If not, which ones are considered optional?

**Comment by philipptrenz** [comment]
@blammit We're currently working on a new motordrive integration and it questions the optional paths currently marked as optional in the dbus specification. 

Therefore: Let's do it as you suggested, hide any path if invalid 👍

**Comment by blammit** [comment]
Will do, thanks 👍
