### ISSUE TITLE
Lynx parallel BMS on WASM not displaying system voltage when BMS is pending

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1522]
If one of the paralleled BMSes is 'pending' (waiting until its voltage level is in range with the system voltage), we show the system voltage in the menu of that BMS. However, on WASM, this field is not set properly:

![image](https://github.com/user-attachments/assets/73f9f524-cc85-417c-8494-00eab7940c15)

On the local UI, the field is showing the value correctly.
See [original issue](https://github.com/victronenergy/gui-v2/issues/1269)

**Comment by DanielMcInnes** [comment]
Hi @ReinvdZee , I will need some help to debug this one. Are you available some time this week?

**Comment by DanielMcInnes** [comment]
dbus path:
dbus/com.victronenergy.battery.lynxparallel1/Dc/0/Voltage

mqtt path: 
mqtt/battery/1/Dc/0/Voltage
