### ISSUE TITLE
Not possible to configure high battery temperature alarm

### ISSUE THREAD

**Issue by RichardTsc** [victronenergy/gui-v2#1543]
In the gui-v2, I went through all menu items looking for a way to configure a high battery temperature alarm. I'm able to configure alarms for high/low tank levels and high/low temperature from my sensors, but not for the temperature sensor from the SmartShunt. In the setup menu for the SmartShunt, I just see a set of pre configured alarms all with "OK" independent on how high/low the temperature is.

<img width="1443" alt="image" src="https://github.com/user-attachments/assets/ff075f9b-ba9c-4334-bd4b-a7ba6092f1e0">

Is this a bug or am I missing the point where I can configure this? To my understanding, the alarms configured in VRM are a different kind of alarms which also do not show on the gui-v2

**Comment by DanielMcInnes** [comment]
Hi @RichardTsc , you should go back one level from there, and click 'Settings'
![Screenshot from 2024-10-07 17-04-48](https://github.com/user-attachments/assets/0160bc3c-309d-41c3-bd52-a73911818d12)

Then click 'Alarms' from inside the 'Settings' page
![Screenshot from 2024-10-07 17-04-59](https://github.com/user-attachments/assets/cb83bdd0-1ec1-431f-ab39-dbc36b0fc1ce)

**Comment by RichardTsc** [comment]
Hi @DanielMcInnes , thanks for the swift reply. Unfortunately, I'm missing exactly this "Settings" item between History and Device. Any idea why?

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/526b9e80-87ee-42a1-bb77-80e2affd83f1">
 
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/dc578e6f-7f25-484a-9836-31d403d895bb">

**Comment by DanielMcInnes** [comment]
Hi @RichardTsc , I don't know sorry. The 'Settings' item is only shown if your smart shunt supports it, eg. from the path `.../battery/2/Settings/HasSettings`. I don't know why your SmartShunt doesn't support it. Try reading this: https://www.victronenergy.com/media/pg/SmartShunt/en/all-features-and-settings.html , it might be something you have to set up via VictronConnect

**Comment by RichardTsc** [comment]
@DanielMcInnes, you are right, I was able to set it up via VictronConnect and it works on the gui-v2 after its set up there. 

Would argue, that it should be able to configure also without VictronConnect, as this is one of the bread and butter shunts and nothing special

**Comment by chriadam** [comment]
Not a bug in gui-v2.  Perhaps a feature request for venus-platform?  Please make a post on the community forum: https://community.victronenergy.com/c/betas/venus-betas/18
