### ISSUE TITLE
Two "Input current limit" fields

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1546]
Seen on [this](https://vrm.victronenergy.com/installation/473156/dashboard) system, running V3.50~28. The vebus system shows two different input current limits, 16A and 50A. 

50A is the input current limit for AC input 1 and the setting is disabled (Configured in VEConfigure). The other one is the input current limit for AC input 2 and can be changed.

![image](https://github.com/user-attachments/assets/90aaf626-6c88-4bfc-9926-2556e9d00dc2)

On gui-v1 the input current limit for AC input 1 is hidden because it cannot be configured.
If we show them both in V2, we should add the AC input number to the field.

**Comment by mpvader** [comment]
Replaced by a new issue made just now. Nice find!
