### ISSUE TITLE
add text to ess menu about rs settings location

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1549]
as per gui-v1 commit https://github.com/victronenergy/gui/commit/25ce2c3541358d84f07722a5309975bc22a85a22

    add text to ess menu about rs settings location
    
    Add text to the ESS menu that shows up if there is an RS system,
    telling the user that the ESS settings can be accessed from the
    device list.
    
    https://github.com/victronenergy/venus-private/issues/404

**Comment by mpvader** [comment]
on my system, which has Multi RS, this either doesn't work, or I don't understand how its supposed to work, @izak 

![image](https://github.com/user-attachments/assets/dc6f67f0-7623-4f24-8fe5-6a04ce451f7e)

https://vrm.victronenergy.com/installation/358999/overview

**Comment by izak** [comment]
Aaah I know! Old wasm on VRM:

![Selection_173](https://github.com/user-attachments/assets/cc473e93-10aa-4477-a362-f9d3f29357d4)

It works correctly with v0.3.15.

**Comment by mpvader** [comment]
👍
