### ISSUE TITLE
add dynamic ess submenu to RS ESS settings

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1550]
as per gui-v1 commit [20c324ef8fc5702d84bfa58c5bb8a30ad10d95d8
](https://github.com/victronenergy/gui/commit/20c324ef8fc5702d84bfa58c5bb8a30ad10d95d8)

    add dynamic ess submenu to RS ESS settings
    
    This allows turning off DynamicEss from the GX device also for
    the RS/HS19, just like with VE.Bus Multis.

**Comment by blammit** [comment]
Done, closing.
