### ISSUE TITLE
Implement connectivity icons

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1552]
Implement the Wifi and cellular connectivity icons in the status bar, as per the design:

![image](https://github.com/user-attachments/assets/47061669-5bf0-4f2e-b4c1-788b6582bbe7)

Not a blocker for V1.0.0.

**Comment by DanielMcInnes** [comment]
Hi @ReinvdZee , I can't find these icons in the design, do you know where they are?

**Comment by nmbath** [comment]
Would it be possible to also have an icon for ethernet being connected?

**Comment by DanielMcInnes** [comment]
> @DanielMcInnes Icons are here: https://www.figma.com/design/GjCtz3A3jqSGvyjVvOm6RZ/GX-Touch-design?node-id=2110-140997&node-type=canvas&m=dev
> 
> But I think you added some components for the GSM settings a while back, to generate the icons for cellular strength? Don't remember if we added something similar for Wi-Fi settings as well.

thanks Bea

**Comment by DanielMcInnes** [comment]
> Would it be possible to also have an icon for ethernet being connected?

We have a meeting later today, I'll bring it up then. @mpvader FYI

**Comment by mpvader** [comment]
hey @nmbath 

> Would it be possible to also have an icon for ethernet being connected?

no; too much clutter.

**Comment by blammit** [comment]
Setting medium priority for 1.1.0
