### ISSUE TITLE
pvinverter: option to enable limiter if supported

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1558]
as per gui-v1 commit c6829d68b3eded79fa3d608e6395d5af53bd9ca1

    pvinverter: option to enable limiter if supported
    
    We're expanding the ability to limit PV-inverters other than
    Fronius and ABB/Fimer. For such inverters, dbus-fronius will
    place a marker value in localsettings that indicate whether
    the setting should be available on this inverter. This allows
    enabling the setting for other inverters, previously not supported.
    
    The setting defaults to enabled.

**Comment by chriadam** [comment]
Fixed.
