### ISSUE TITLE
PageSettingsGeneral: rename Security Level to Network Security Level

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#1559]
as per gui-v1 commit 6a35a8db57e6e9f750afd17c4523702d64d0a274

    PageSettingsGeneral: rename Security Level to Network Security Level
    
    Just to make it clearer that this settings only affects Network services.
    Move the setting below the Access Level instead of the top of the page.

**Comment by blammit** [comment]
@DanielMcInnes this is a duplicate of #1541 that you already fixed? Closing.
