### ISSUE TITLE
Charging plan duration empty

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#1570]
If I set a charging duration greater or equal to 24 hours under Settings -> ESS -> Scheduled charge levels -> Schedule -> Duration (hh:mm) then the field gets empty.

![grafik](https://github.com/user-attachments/assets/ee209b8b-c2d7-401b-be10-397c8bea30fd)

![grafik](https://github.com/user-attachments/assets/5773c2a4-0570-42e5-a788-a5af2e131d2f)

![grafik](https://github.com/user-attachments/assets/996ae22a-1782-4b73-af31-100987880e37)

**Comment by blammit** [comment]
Sounds straightforward to fix, setting medium prio.
