### ISSUE TITLE
Control panel card for ESS is missing for RS systems

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1571]
See below for how it looks for VE.Bus systems. On an RS system, no entry in the control pane shows up. What is fundamentaly different here is that for VE.Bus systems, ESS control goes via `com.victronenergy.settings /hub4control`; and for RS systems, as well as any other new type Victron inverter/chargers, its in `com.victronenergy.acsystem/*`

First step here is @izak to outline exactly how this is supposed to work.

- [ ] Specify the details (dbus paths, etc). (@izak)
- [ ] Implementation (Qinetic)

![image](https://github.com/user-attachments/assets/9d60404a-26a8-4dad-9a5c-24c4a32a5260)

**Comment by mpvader** [comment]
There is a PR for this

**Comment by blammit** [comment]
Fixed by https://github.com/victronenergy/gui-v2/pull/1681
