### ISSUE TITLE
Show confirmation dialog on reboot

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1577]
In Settings > General, when "Reboot now" is clicked, show a confirmation dialog with OK/Cancel options so that the user can cancel this action if it was accidentally clicked.

**Comment by philipptrenz** [comment]
May I also suggest to change the wording on the popup after confirming the reboot. Currently it instantly shows „Device has been rebooted“ after pressing the reboot button, but this is obviously not the case.

Something like “The device is now restarted. The connection will be re-established as soon as the restart is complete.”
would be more helpful. Also the icon could be a bit more neutral, I guess.

![IMG_0061](https://github.com/user-attachments/assets/38dd8ad4-dbe7-4fcb-a79c-a7efee90ce44)
