### ISSUE TITLE
Solar charger not showing active error

### ISSUE THREAD

**Issue by martinbosma** [victronenergy/gui-v2#1578]
See https://github.com/victronenergy/venus-private/issues/453

It appears the active error (`/ErrorCode`) is not shown on the Alarms & Errors page and the last errors (from history) are indicates as if there is an error. This is not true, although the active error is pushed into the last errors as soon as it occurs, but is never cleared.

Tested on a MPPT RS by inducing error 121.

On the device list summary it shows the error:
![376539529-0e61526d-f21e-4e6e-843e-c5c76a57f8c1](https://github.com/user-attachments/assets/be2afc23-117c-4998-9d49-f5069fc571eb)

Nothing on the device page, but it falsely implies there are 4 active alarms/errors:
![376539766-afba02bc-c501-426c-a735-fd01fee49afa](https://github.com/user-attachments/assets/22374483-fac7-4d9f-a4ac-b9da7147cbc1)

Alarms & Errors does not show active error, only the last errors from history:
![376540067-86c63d96-e86c-4893-b518-6f93921f483d](https://github.com/user-attachments/assets/3b482da1-1b34-4618-9dcb-36128b9eab85)

**Comment by martinbosma** [comment]
@blammit Can you fix the following items?
- Add the active error to the Alarms & Errors page?
- Drop the Last errors from Alarms & Errors
- Fix the "error counter" to only include active `Alarms/*` items and the `ErrorCode`
- Perhaps prefix the error code on the summary with a #, e.g. `Error: #121`

**Comment by blammit** [comment]
@martinbosma should the "Last errors" really be dropped from Alarms & Errors? If we drop it, there is no other way to view the `/History/Overall/LastError*` for the charger.

I could just add the active error to the Alarms & Errors page, but without removing the Last Errors, but rename it to "Overall error history"? For example, here is an updated version, with:

- active error added to the Alarms & Errors page
- "error counter" changed to only include the active Alarms/* items and the ErrorCode

![image](https://github.com/user-attachments/assets/61237d8a-5574-4a93-a29f-a46afc2279b1)
![image](https://github.com/user-attachments/assets/f6319cdc-caee-4234-9ec6-d968bebcb1a5)


> Perhaps prefix the error code on the summary with a #, e.g. Error: #121

Sounds good, or alternatively we could show the full error description here instead, if that is preferable?

**Comment by blammit** [comment]
> Perhaps prefix the error code on the summary with a #, e.g. Error: #121

@martinbosma  Sounds good, or alternatively we could show the full error description here instead, if that is preferable?

**Comment by martinbosma** [comment]
>should the "Last errors" really be dropped from Alarms & Errors? If we drop it, there is no other way to view the /History/Overall/LastError* for the charger.

@blammit I discussed this with Matthijs yesterday and we decided to drop the last errors for now, until we have a better design.

>Sounds good, or alternatively we could show the full error description here instead, if that is preferable?

I'm afraid not all (translated) error descriptions will fit there. Do you have any insights in that? Otherwise just stick with the number.

**Comment by blammit** [comment]
> @blammit I discussed this with Matthijs yesterday and we decided to drop the last errors for now, until we have a better design.

Okay, sounds good, thanks.

> I'm afraid not all (translated) error descriptions will fit there. Do you have any insights in that? Otherwise just stick with the number.

There is a bit of space available, but it doesn't wrap at the moment:

![image](https://github.com/user-attachments/assets/226bad48-40b4-4b29-bd4e-8dac027deaa3)

For 1.1.0 I'm planning some [reworking of the Device List implementation](https://github.com/victronenergy/gui-v2/issues/1339) to make custom per-service UI items, which will make it easy to wrap the error text, so we could add it at that point.

**Comment by martinbosma** [comment]
>So I can just use the number for now. For 1.1.0 I'm planning some https://github.com/victronenergy/gui-v2/issues/1339 to make custom per-service UI items, which will make it easy to wrap the error text, so we could add it at that point.

Let look at this again when you are working on that issue.
