### ISSUE TITLE
Increase sensor value limit precision

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1587]
Currently, sensor value limits can be specified with 1 digit of precision:
 
![image](https://github.com/user-attachments/assets/1c9768d1-1a86-4839-a7ed-c814900a91c8)

This should be increased to at least 2 digits or maybe even 3 digits. 
The smallest step the analog inputs can take is 0.005V. 

I tested with a power supply and multimeter, the reported value of the ADC can be off by a few mV (e.g., multimeter reports 724 mV, GX reports 0.72V).

I think 2 digits for setting the sensor limits is sufficient. @mpvader?

**Comment by mpvader** [comment]
Lets change it to two digits

**Comment by mpvader** [comment]
From the user:

> Safiery Ultrasonics attached to a GX tank.
> 0 - 4v at maximum tank height (1 metre) but on a smaller tank it’s less. On my tank the range is 0.6v
> The GX Tank reads in .005 volt steps. It would be nice to be able to configure in those steps, or simply a button that says “set min” or “set max” which reads the current value to 3 decimal places and sets the min/max.
> I’ve had to use dbus-spy to get mine configured correctly.

so, on a second thought,  why not simply allow setting it in steps of 0.005V?

Its a bit extreme, but as long as the UI is smart enough wrt accelerating when keeping the button pressed, or add those set min and set max options, then I don’t see why not.

https://community.victronenergy.com/t/bug-sensor-value-a-writeable-field-in-v3-50-24/5179
