### ISSUE TITLE
Reword fw version updated detected page

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1592]
Hi please:

1. change the icon to something less alarmistic, an (i) for example. 
2. change title (Firmware version update detected) to GX Device has been updated

![image](https://github.com/user-attachments/assets/2c760644-fea4-4a0a-97ec-e8d4e79d7d06)

**Comment by blammit** [comment]
Making PR to show this instead:

![image](https://github.com/user-attachments/assets/92927599-cf8c-4acd-9624-e69ee4436339)
