### ISSUE TITLE
Add EVCS control card

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1593]
Add a control card for each EVCS service. It should show similar data to the control card in VRM:

![image](https://github.com/user-attachments/assets/b0f19e9b-1d12-4863-a66a-306c20c1671d)

**Comment by MikeTrahearn-Qinetic** [comment]
Should there be one control card for each EVCS?

**Comment by blammit** [comment]
> Should there be one control card for each EVCS?

Yes.

**Comment by MikeTrahearn-Qinetic** [comment]
@blammit  There is quite a lot that can be done here and I have gotten a new card with a few test control working on it already. However we should decide on actual UI design for this based on existing UI precedents, for example the Inverter/Charger Control card and its various controls and the existing EVCS Settings controls.

**Comment by MikeTrahearn-Qinetic** [comment]
Screen shots of work in progress - EVCS Cards are now working showing the name, status, mode, current and charging; current is only enabled when the mode is manual as per the EvChargerPage.

<img width="256" alt="EVCS Cards - Light" src="https://github.com/user-attachments/assets/6785c8fb-9dbb-4885-9185-c9051e28b4dd">
<img width="256" alt="EVCS Card Mode - Light" src="https://github.com/user-attachments/assets/39303502-5b6e-4638-9ade-eaec92c6b6f7">
<img width="256" alt="EVCS Card Current - Light" src="https://github.com/user-attachments/assets/0bb9f6fb-ff76-49d0-ad0d-e2fad2194d1e">
<img width="256" alt="EVCS Cards - Dark" src="https://github.com/user-attachments/assets/976fce91-6748-4308-b0cb-a3272e08544d">
<img width="256" alt="EVCS Card Mode - Dark" src="https://github.com/user-attachments/assets/135f6387-9f4c-4fc1-bfd1-737998fe7a05">
<img width="256" alt="EVCS Card - Current - Dark" src="https://github.com/user-attachments/assets/2ec02905-1968-49bc-a9ef-e64b78548f08">
