### ISSUE TITLE
Adjust conditions for showing arrow icon for positive/negative AC power on Brief/Overview

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1595]
When showing the power for the active input on the Brief page (top-left gauge) or Overview page (Grid/Shore/Generator):

- When the power is negative, show the green arrow (pointing left), and don't show a minus symbol. Do this regardless of whether ESS feedback is enabled.
- When the power is positive, only show the blue arrow (pointing right) when ESS feedback is enabled.

Also, update the "ESS feedback to grid" check in SystemSettings.qml to simply check for  `com.victronenergy.system/Ac/ActiveIn/FeedbackEnabled = 1`. This allows the check to work on RS systems as well, unlike the current implementation that checks the value of `/Hub4`, `/Settings/CGwacs/OvervoltageFeedIn` and `/Settings/CGwacs/PreventFeedback`.

**Comment by mpvader** [comment]
https://victrondevelopment.slack.com/archives/C020QG3JVEW/p1729160215114419

**Comment by blammit** [comment]
Changes merged.
