### ISSUE TITLE
Fix heatpump related issues

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1598]
Mandatory for v1.0.0 / v3.50:
- [ ] Hide the heatpump option from the Role list for now: don't allow users to change the AC role into that option, but for meters already having that selected - leave it visible. 

Optional / for later:
- [ ] Make com.victronenergy.heatpump show up in the device list; but that first needs a good spec: ie what value do we show there. Could be that its clear in gui-v1 already - but now I don't know and its not urgent.

### details:

What happens: if user either in gui-v2 or gui-v1 sets the role of an energy meter to be Heat pump, then it goes onto dbus as heatpump and because gui-v2 doesn't have that yet its then totally gone and user can't make it come back.

Its probably most straight forward to quickly an entry for it as a device list, by copying the AC load code and see that as heat

Example here:

- story here: https://community.victronenergy.com/t/os-v3-50-28-em24-ethernet-disappeared/6251/4
- slack: https://victrondevelopment.slack.com/archives/C7C1ZU6UD/p1729192326853679

**Comment by martinbosma** [comment]
@mpvader That would be Tuesday then. Today and Monday I'm not available.
