### ISSUE TITLE
Onboarding is stuck?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1601]
On this system, https://vrm.victronenergy.com/installation/151755/diagnostics, 50ft yacht demo system in our lab, while running Venus OS v3.50~34, three people, including me, had the issue that they couldn't in the end close the onboarding pages - while operating in WASM.

Both the SKIP and the CLOSE button didn't work.

I didn't see any relevant messages in the dev. console of the browser.

Also haven't heard anyone else complain about the same, which is strange since by now there must have been 1000s of people that have seen the onboarding page.

Just in case its relevant: the onboarding setting does exist in localsettings, and setting that to 0 immediately closed the onboard for me. Which was nice, since this is a demo system which marketing dept. is using to make screenshots required for the launch of gui-v2.

So; at least do a review of the code to see if there is some condition or similar in which case the onboarding page refuses to close?

**Comment by mr-manuel** [comment]
As additional information:
I tried on 4 different devices and it worked on all as it should:
1. Already setup Ekrano GX with 3.50\~31 updated to 3.50\~34.
2. Already setup Cerbo GX with 3.50\~33 updated to 3.50\~34
3. Already setup Raspberry Pi with 3.50\~22 updated to 3.50\~34
4. Brand new Cerbo GX with 2.91 updated to 3.50\~34

**Comment by blammit** [comment]
I'm not sure what's going on here. Clicking the done/skip buttons just writes the updated value to the `/Settings/Gui2/OnBoarding` data point, and the VeQuickItem object should stay alive until it is closed by the parent `SplashView`. But in case there is something stopping the onboarding view from writing to the dbus/mqtt backend, I've made a fix that forces the onboarding view to be closed, even if `/Settings/Gui2/OnBoarding = 0`. 

So, worst case is that the onboarding will still appear on the next run, but at least the user will be able to skip it.

**Comment by mpvader** [comment]
👍

**Comment by mpvader** [comment]
Maybe the issue was read only access over VRM

**Comment by blammit** [comment]
Aha, that makes sense. Should the onboarding be disabled when it's read-only access then? Otherwise the onboarding will always show up for these users.
