### ISSUE TITLE
Overview: Inconsistent "wiring" of the EVCS tile

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/gui-v2#1624]
EVCS tile should always be connected to either "AC Loads" or "Essential Loads", but never "Inverter/Charger". Currently, that's not the case if there is only a "AC Loads" and no "Essential Loads" tile.

![192 168 254 95_gui-v2_(Ekrano GX)](https://github.com/user-attachments/assets/e6fe20f8-8398-496c-9d7a-cea4648d4646)

**Comment by blammit** [comment]
Also see discussion here: https://victrondevelopment.slack.com/archives/C020QG3JVEW/p1725894482052949
