### ISSUE TITLE
Battery widget redirects to Multi instead of battery

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#1628]
On this sytem: https://vrm.victronenergy.com/installation/102195/dashboard

The battery widget redirects the user to the Multi, while it should redirect to the Battery page.

[Screencast from 24-10-24 09:59:40.webm](https://github.com/user-attachments/assets/b34d6318-01b3-4a90-b899-b29cae2e0b77)

The battery is provided by `com.victronenergy.battery.socketcan_vecan1` and the multi by `com.victronenergy.acsystem`  (or `com.victronenergy.multi.socketcan` )

**Comment by mpvader** [comment]
Solved, by changing the settings in Settings -> System setup: I've changed the battery monitor from Multi HV to Pylon HV
