### ISSUE TITLE
Entry in the device list doubles after changing settings?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1631]
first step is to see if this is reproducible.

https://community.victronenergy.com/t/small-bugs-3-50-37/8943/4

Note that Item two in that post, a suggestion, has been listed listed elsewhere already to look into later (gui-v2 doc). No need for action on that. 

for me this  bug is not a blocker for v3.50 release. Totally ok to leave it, to prevent breaking other things if fix is non trivial.

![IMG_3335](https://github.com/user-attachments/assets/8e9f2ce7-f7a9-43aa-9320-b4b2e3980e80)

**Comment by blammit** [comment]
Can confirm that I can reproduce this:

- open the Device List, click on a tank and then open "Setup"
- Change the "Fluid type"
- Go back to Device List and observe you have the original tank, as well as the new one with the modified fluid type
