### ISSUE TITLE
VRM Portal setting is not set back to full when clicking cancel

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1633]
This is about the Are you sure popup thats shown when in WASM as a user changing the VRM Portal setting from Full to something else.

When I click cancel, it says Read-only. I expect it to then have gone back to Full.

![image](https://github.com/user-attachments/assets/4b3fc722-e65a-4a0d-bffb-7be277ea9932)

**Comment by chriadam** [comment]
I will take this one.  I hope the fix is basically just to set the "don't update currentIndex on click" flag.

**Comment by chriadam** [comment]
Fixed.
