### ISSUE TITLE
VE.Bus AC Input 1 and 2 issues

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1637]
@vejpasop I encountered this by accident, while looking into an unrelated issue where the current limit of EVCS can't be set via gui-v2. Please take this over from me, test more completely and propose how it should be work + list of test conditions.

(Possible) issues that I've seen: 

### 1. Both the input current limit entries shown in the list have the same name.

Whats expected instead is that they have different names; or we show just one.

Twice the same name in the control card:
![image](https://github.com/user-attachments/assets/09998fc9-46df-4e8d-a5f6-c023665f46eb)

Twice the same name shown in details page:
![image](https://github.com/user-attachments/assets/c95ddd47-9e3b-4a3b-be8d-be0cfe89bec7)

### 2. the 50A is shown as editable but its not

Better to show it as a non-editable version right from the get go and a toast explaining why when user clicks that.

![image](https://github.com/user-attachments/assets/5d022c04-fbad-431d-beb9-be3379ba2bb3)

### 3. Notification text needs amending. 

It now says "This setting is disabled. Possible reasons are "Overruled by remote" is not enabled or an assistant is preventing the adjustment. Please, check the inverter configuration with VEConfigure". In 99% of cases, its disabled by design by the installer, lets not tell end-users to go into VEConfigure.

New text: "This current limit is fixed in the system configuration, it is not possible to adjust it".

**Comment by blammit** [comment]
PR https://github.com/victronenergy/gui-v2/pull/1643 fixes this.

Note that this only works if the vebus service is the primary one on the system, according to `com.victronenergy.system/VebusService`. Otherwise, it is assumed the `/SystemSetup/AcInput<X>` cannot be applied for this vebus service, and it will still just show "Input current limit" instead of something more specific.

**Comment by vejpasop** [comment]
Successfully tested on Venus V3.50~42.  
![image](https://github.com/user-attachments/assets/75172fff-ce73-46c2-a39c-3193337ff7c7)
![image](https://github.com/user-attachments/assets/5f6fce3b-d90d-4e9e-a2cf-f134db2e6d66)
![image](https://github.com/user-attachments/assets/f12f40bc-92ce-4361-808e-56a1e8abc154)
![image](https://github.com/user-attachments/assets/6ae8ef18-7804-4671-bfbc-aa146ddd137c)
![image](https://github.com/user-attachments/assets/66b85489-1d76-410b-8c2d-35b74b7be399)
![image](https://github.com/user-attachments/assets/7913944b-b324-43b3-9669-cd880db06897)

**Comment by izak** [comment]
There is still an issue here. After this change, for acsystem services (Multi-RS) the mode is no longer adjustable.

![Selection_186](https://github.com/user-attachments/assets/e6c71b9c-b14d-4e69-821f-fd593b86c7d3)
