### ISSUE TITLE
PV inverters: Add IP address manually changes not saved

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#1655]
When manually adding an IP address under Settings -> PV inverters -> Add IP address manually -> Click on + icon, then the IP default address is added, but the changes to the IP entries are not saved.

![venus-os_pv-inverters](https://github.com/user-attachments/assets/6cfcfa0b-6592-4ac9-8419-7c0387615585)

**Comment by mpvader** [comment]
This means that its not possible to manually add pv inverters?

so effects all systems with pv inverter outside subnet/vlan.

no problem for pv inverters in same sub/net vlan - since they’ll be found by normal scan.

right @mr-manuel ?

**Comment by mr-manuel** [comment]
Yes that is correct. Only relevant for PV inverters in another subnet/vlan.
