### ISSUE TITLE
Ukrainian translation of battery and settings menu header

### ISSUE THREAD

**Issue by dirkjanfaber** [victronenergy/gui-v2#1661]
In Ukrainian the word "Battery" no longer gets translated into  "Батарея". See https://github.com/victronenergy/gui-v2/blob/main/i18n/venus-gui-v2_uk.ts#L4425

Strangely enough this is not problem for other languages, which correctly translate the term. 
![image](https://github.com/user-attachments/assets/89a4a390-47f5-4dfd-af12-04bd9520b427)

And before v3.50~37 it was working correctly:
![image](https://github.com/user-attachments/assets/56414c42-759e-4760-b3ff-748db2857909)

Feel free to test on https://vrm.victronenergy.com/installation/102195/dashboard

And also noticing that, when you switch translations, the menu header doesn't get updated until you re-enter the settings menu.
![image](https://github.com/user-attachments/assets/b7affaca-45aa-4e0a-af66-a9998efba610)

**Comment by podarok** [comment]
Tnx

**Comment by imval** [comment]
There is a similar issue for the French translation with the word "Automatic" that is not correctly translated in the UI in a few places, even though the key is present in Poeditor (the translation platform).
![image](https://github.com/user-attachments/assets/06ff772f-3eaf-4cd4-a9df-1be5e129ad09)
![image](https://github.com/user-attachments/assets/cfe23ab7-7ed1-4016-943e-7813069911b7)

Dirk-Jan asked me to add this in this issue.

**Comment by podarok** [comment]
title seems like not only Ukrainian related @dirkjanfaber 
I have no rights to change it, on you

**Comment by chriadam** [comment]
The id for the "Battery" string is "common_words_battery", but this is missing from the locale-specific .ts files in the repository, although it IS present in the locale-specific .ts file in the build artifacts directory, from which the .qm files are generated... Interestingly, the translation is marked as "unfinished" there!

```
    <message id="common_words_battery">
        <location filename="../../gui-v2/components/CommonWords.qml" line="83"/>
        <source>Battery</source>
        <translation type="unfinished">Батарея</translation>
    </message>
```

**Comment by chriadam** [comment]
I think we're running lrelease "too soon" i.e. on a version of the .ts which hasn't been properly updated by lupdate.
We have some dependency logic in the CMakeLists.txt file to try to enforce proper ordering, but it seems like this might be failing.

**Comment by dirkjanfaber** [comment]
The cause for the `unfinished` marking seems to come from the fact that some translations are marked as "fuzzy" within poeditor.   Even though that seems to be unrelated, I will ask the translators to check these fuzzy ones too and unmark the fuzzy checkbox if they have proofread it.
The rabbit hole on fuzzy translations can be found [here](https://poeditor.com/kb/fuzzy-translations). 🐰

**Comment by dirkjanfaber** [comment]
Did test with the build from https://github.com/victronenergy/gui-v2/actions/runs/11626874251. Though "Battery" is correctly translated for Ukrainian, it isn't the case for "Automatic" in French. 

![image](https://github.com/user-attachments/assets/40e2fb81-23ff-4348-98c6-279468056014)

While it is translated correctly on the ethernet configuration. 😕 
![image](https://github.com/user-attachments/assets/657f9671-e39b-4400-a0c9-0c40e69a5891)

Can it be that only one instance of the term actually gets translated?

**Comment by chriadam** [comment]
Thanks, closing as fixed.
