### ISSUE TITLE
Solar detail pages show errors for spurious MPPT RS

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1662]
you can use this test system: 

https://vrm.victronenergy.com/installation/55013/overview

There are no errors, so the count is wrong:

![IMG_3351](https://github.com/user-attachments/assets/90f30ab9-b9a5-4a14-b77c-5ada2c9cc648)

**Comment by mpvader** [comment]
This one should be simple to fix @blammit ?

and many people notice this; pls prioritise this one

**Comment by chriadam** [comment]
On our system, the path: com.victronenergy.solarcharger.ttyUSB1/Alarms/LowVoltage etc don't exist, and so the "isValid" check (correctly) fails, and no error is shown.  But, on other systems, the path might exist, but the value might be zero (i.e. "this alarm isn't set").  So we need to update the condition to not just check isValid but also whether value != 0, I guess.

**Comment by chriadam** [comment]
Fixed.
