### ISSUE TITLE
Swap ESS menu items so its same sequence as elsewhere

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#1683]
because changing things like this is very annoying for people used to it, lets do it asap.

wanted order in the menu:
1. Optimized with
2. Optimized without
3. Keep batt
4. Ext. control

![IMG_3379](https://github.com/user-attachments/assets/ceb3dfe3-77b7-4c5e-84fb-3051e4d87acf)
![IMG_3378](https://github.com/user-attachments/assets/4f6e85cf-cfcc-44fb-87bc-1a754d3ee888)

VRM:

![IMG_3377](https://github.com/user-attachments/assets/f450b6d5-f7db-4ac7-b5eb-4bf789195cb6)

from: https://community.victronenergy.com/t/ess-mode-list-in-different-order-v2-new-menu-structure-makes-me-scroll-a-lot/9991/2

**Comment by chriadam** [comment]
Fix merged to main.  Closing.
