### ISSUE TITLE
VE.Bus restart does not work after a fresh boot

### ISSUE THREAD

**Issue by izak** [victronenergy/gui-v2#1701]
The /SystemReset path comes up as invalid after a reboot, causing the option to be disabled:

![Selection_192](https://github.com/user-attachments/assets/28ce7085-4c0a-4f96-bbba-797ecc373ecb)

I looked at how this was done in the old GUI, and I'm unsure what the idea was. The button is "editable" if the path is valid, and once you pressed it once it gets that little triangle, but in all cases you can reset the VE.Bus regardless of whether the path is valid or not. So this is a regression in GUI-v2.

**Comment by blammit** [comment]
Fixed by https://github.com/victronenergy/gui-v2/pull/1702
