### ISSUE TITLE
Settings: clicking on the top row causes the Generator Start/Stop menu option to be triggered

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#1714]
See thread and video here: https://victrondevelopment.slack.com/archives/C04RYU0UMDE/p1731142689206319

**Comment by MikeTrahearn-Qinetic** [comment]
I need access to the victron slack to be able to view the issue details.

**Comment by blammit** [comment]
(Access has been provided now)

**Comment by MikeTrahearn-Qinetic** [comment]
I have been able to reproduce this.

**Comment by MikeTrahearn-Qinetic** [comment]
On investigation it has been found as suspected that the clickable delegates in the Settings list view are not being clipped by the view and are thus clickable through the status bar - AND the navigation bar.
The image below shows this happening clearly as I have made the status and navigation bar slightly transparent, showing the obvious problem in the annotated red areas.
<img width="912" alt="Settings Not Cropped" src="https://github.com/user-attachments/assets/d55ffa24-8e35-45b2-9db0-aba8e7cee013" />

**Comment by MikeTrahearn-Qinetic** [comment]
Adding clipping to the GradientListView in pages/SettingsPage.qml fixes this issue.

**Comment by MikeTrahearn-Qinetic** [comment]
- [ ] Test on Desktop
- [ ] Test on WASM
- [ ] Test on Cerbo
