### ISSUE TITLE
Consider configuring Qt VKB UI options

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#206]
We might need to configure the Qt VKB. In our default version, for example, the i18n key shows a default list of language options including American English, Spanish etc. but we should only show the supported languages.

**Comment by chriadam** [comment]
We want to enable the Qt VKB on CerboGX, but we want to disable it for WebAssembly (since the user should be using the native iOS / Android VKB on those platforms, and the hardware keyboard on the desktop platform).

**Comment by chriadam** [comment]
Basically, we just need to check (after translations support has been properly included) that the Qt VKB on CerboGX is switching properly when the language changes.  It should already work, we just need to confirm.

No changes should be needed from us.

**Comment by blammit** [comment]
> Basically, we just need to check (after translations support has been properly included) that the Qt VKB on CerboGX is switching properly when the language changes. It should already work, we just need to confirm.

Note, translation support will be fixed by https://github.com/victronenergy/gui-v2/issues/573

**Comment by blammit** [comment]
> but we should only show the supported languages.

This is already done.
