### ISSUE TITLE
10.i MQTT support for notifications& alarms

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#229]

**Comment by mpvader** [comment]
An update: Jesus finished his work and currently its being reviewed by Jeroen:

https://github.com/victronenergy/venus-platform/commits/jperez/WIP_platform_alarms

**Comment by chriadam** [comment]
As far as I know, this is still awaiting review / blocked.  Adding high_prio tag.

**Comment by chriadam** [comment]
No longer blocked, ready for work.
