### ISSUE TITLE
Use Qt timezone lists in timezone settings

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#299]
Instead of using the lists from gui-v1, use Qt's timezone lists instead: https://doc.qt.io/qt-6/qtimezone.html

(See also: bug for gui-v1 https://github.com/victronenergy/venus/issues/434 for relevant comments)

**Comment by chriadam** [comment]
This cannot be implemented because Qt for WebAssembly doesn't support QDateTime and QTimeZone.
Closing as WONTFIX.
