### ISSUE TITLE
Brief page abruptly switches between single and multi-gauge display on first load

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#306]
The tank model may not be fully loaded by the time the Brief page is initially shown; this leads to an abrupt switch from the single to multi-gauge display.

We should delay hiding the loading screen until all Brief page data is ready (tank models, AC/DC input models, solar models, consumption data).

**Comment by chriadam** [comment]
https://github.com/victronenergy/gui-v2/pull/585 does this.  Haven't seen the flicker issue since then.

This issue is now fixed, closing.
