### ISSUE TITLE
Retained messages - problems, work-around and plan

### ISSUE THREAD

**Issue by wiebeytec** [victronenergy/gui-v2#313]
**Short version**: we are going to stop using retained messages once we replace [dbus-mqtt](https://github.com/victronenergy/dbus-mqtt) with something that can publish very fast, and in the interim, provide a temporary ability to request a publication of all topics (https://github.com/victronenergy/venus/issues/1065) and guiv2 should reject messages with the `retain` flag set, once this feature is used.

**Details**:

The current [dbus-mqtt](https://github.com/victronenergy/dbus-mqtt) publishes everything as 'retained', so that when you connect with a client, you can instantly see all topics for an installation, without the need for republication. The dbus-mqtt service also takes care of _unpublishing_ when devices disconnect.

The problem is that while this idea works locally, it doesn't on the internet servers. Devices can be unplugged while the GX device is offline. An _unpublish_ will then never happen. This leads to stale topics, and the need to do `R/portalid/path` requests.

**Solution**:

Not using retained messages. Dbus-mqtt will be fitted with a temporary keep-alive system that will force-publish all topics, even when it's alive. This will be deployed only the beta releases of Venus, for developers and users of GUIv2.

The Python dbus-mqtt service is being replaced with one that is much faster, and has far greater bulking abilities, so publishing all topics on receiving `R/<portal ID>/keepalive` will become the default, and it will likely contain an additional flag to suppress republication, specified in the payload. In this way we retain compatibility with old clients, yet reduce load caused by new.

Because the server still has these retained messages, you need to manually ignore them. Messages that you receive as 'retained' have the `retain` flag set, so they can be dropped.

**Comment by blammit** [comment]
Fixed now, as per the commits linked in this task.
