### ISSUE TITLE
Add Device List in settings

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#328]
As per thread with Mathijs:

Current version of the gui, gui v1, has a device list. And entry point into the settings menu is at the bottom of that. And that device list is something that users often have to use on day to day using and monitoring the system.

In the new gui, the overview page, brief page, controls, as well as click-through pages like we have for solar make it such that the a device list is no longer needed on day to day basis by the user.

But we still need it. The idea:

- in the new settings menu, add an entry called device list.
- In that list, have a list of all devices (= dbus services) just like today gui, preferably including that summary of device state thats on the right in the table/listview in gui-v1.
- wrt design of each of those pages its simple: the qml pages can be copied / migrated from old gui to new gui.

There is one exception: for solarchargers you should use the already designed and implemented page for that.

Note: await further advice from Jesús in regards to how the gui-v1 pages should be ported.

**Comment by blammit** [comment]
The majority of the Device List sub-pages have been implemented (or have PRs pending). I've created tasks for those remaining (excluding those marked as "not yet / for later"): 

pulsemeter https://github.com/victronenergy/gui-v2/issues/594
digitalinput https://github.com/victronenergy/gui-v2/issues/595
meteo https://github.com/victronenergy/gui-v2/issues/596
inverter https://github.com/victronenergy/gui-v2/issues/597
temperature https://github.com/victronenergy/gui-v2/issues/598

**Comment by blammit** [comment]
The PRs listed in the previous comment have been merged in version [0.2.4](https://github.com/victronenergy/gui-v2/releases/tag/v0.2.4).

In summary, all the sub-pages have been done, aside from these as they were listed as "not yet / for later":

- com.victronenergy.multi.xxx
- com.victronenergy.charger.xxx

These were also marked as "not yet / for later" but have been done anyway:

- com.victronenergy.motordrive.xxx - this was trivial to add
- com.victronenergy.alternator.xxx - this was added as part of the DC support in the device list

**Comment by chriadam** [comment]
We have separate tasks to track the lower-priority / not-for-first-release device types (#594, #595, #596, #597, #598) so closing this task as DONE.
