### ISSUE TITLE
Access level checks seems to be missing

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/gui-v2#405]
There are a lot a place where the access level isn't checked

For example:
We don't want to allow customers to accidentally check develop for an update feed, that is even before ci checked if there are no extreme stupid bugs. It will simply install anything coming from the builder _before_ any checks are run on it. That should not an option for end users.

Idem with several Debug menus etc.

**Comment by blammit** [comment]
This has been done now, as per the linked commits. Closing.
