### ISSUE TITLE
qsTrId

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/gui-v2#407]
More a question then an issue. The use of ids seems more complicated than using English. Why would you want to use ids? poeditor should auto suggest changes afaik, with ids you leave the translators to guess how punctuation etc are done.

**Comment by chriadam** [comment]
@dirkjanfaber has a PR to integrate gui-v2 with the translation backend, and the translation ids seem fine / not problematic with that system, so closing this issue as wontfix.
