### ISSUE TITLE
1.0.2 PageInverter: Add support for active phase being L2 or L3

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#410]
See gui-v1 commit dc66b29f93714460596b2f91c5b0833396e1328f

    PageInverter: Add support for active phase being L2 or L3
    
    Currently there is beta firmware that allows the Inverter RS to be
    configure in a 3 phase system. Venus OS is not yet prepared for this,
    i.e. all individual devices are visible on the device list and totals
    are not supported. Nor is there any work done on the overview page.
    
    This change adds the minimum, to at least show L2 and L3 data on the
    device page of an inverter.

**Comment by blammit** [comment]
Done as part of PageInverter
