### ISSUE TITLE
ESS status numbers are not shown in gui-v2

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#424]
In gui-v1 the bottom of the screen shows ESS status numbers, like this:

![image](https://github.com/user-attachments/assets/f2a04f09-79a4-46ed-8b89-6b4b6329e33a)

This “ESS#1” at the bottom of the screen is showing the state of values under com.victronenergy.system/SystemState, e.g. SystemState/LowSoc, SystemState/BatteryLife. 

@jepefe Do we need to add this info somewhere? (If so, maybe it could be added to the ESS control cards?)

**Comment by blammit** [comment]
Design has been provided. See "Battery charge/discharge is False" in Figma: the ESS number is added to the battery details on the Overview and Brief pages.

**Comment by DanielMcInnes** [comment]
@blammit , I can't find the design for this, is it at https://www.figma.com/design/j9qNQjp1rHQSbJZRy0sxvk/GX-Touch---Implementation?node-id=203-4359&node-type=canvas ?

**Comment by DanielMcInnes** [comment]
@blammit should this task include the diagonal lines styling changes?

![Screenshot from 2024-10-22 11-22-48](https://github.com/user-attachments/assets/80e5a26d-230b-425c-9bde-d64edffb6b92)

**Comment by blammit** [comment]
@DanielMcInnes no, just the ESS number. The diagonal styling is a separate thing to improve the battery charging state UI.

**Comment by mpvader** [comment]
as discussed, at least for now we're putting this code in the inverter box, since more space.

and only the code, not the text and also no stripes or other things - thats all for later.
