### ISSUE TITLE
Investigate upgrade to Qt 6.5.x for WASM and desktop builds

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#441]
Investigate an upgrade to Qt 6.5.x.

For starters, just build/verify on Qt for WebAssembly and desktop. Device builds will be done separately.

Qt 6.5 requires Emscripten 3.1.25. See https://doc.qt.io/qt-6/wasm.html

**Comment by chriadam** [comment]
As discussed on Slack, Qt 6.5.4 is closed/commercial only, so we actually need to upgrade to Qt 6.6.x.
The builds are already using Qt 6.5.x, so closing this task as DONE.
