### ISSUE TITLE
Investigate using MultiEffect instead of OpacityMask in ShinyArc

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#457]
Currently we use Qt5Compat module solely for the OpacityMask effect to implement the shine effect on gauges.
We should port to the new MultiEffect when possible, so that we can get rid of that module from the build (which will reduce size also).

See https://www.qt.io/blog/a-short-guide-to-qt-quick-effects

**Comment by blammit** [comment]
@chriadam is this done now? Or we can remove the blocked tag since we have upgraded Qt now?

**Comment by chriadam** [comment]
Yeah, this issue is done now.  But now I am looking into pure shaders instead, since we can animate the progress bar more performantly.

**Comment by chriadam** [comment]
Closing as above.
