### ISSUE TITLE
Venus OS Large features dont work

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#468]
See image below. Both of them don't work.

To test this yourself, install Venus OS Large (see here for how to do that https://www.victronenergy.com/live/venus-os:large).

No other Victron equipment is needed.

Here is how check the end result on the command-line:

```
root@einstein:~# svstat /service/node-red-venus/
/service/node-red-venus/: down 217 seconds
root@einstein:~# svstat /service/signalk-server/
/service/signalk-server/: up (pid 1660) 201 seconds, normally down
```

![image](https://github.com/victronenergy/gui-v2/assets/5200296/e06e8ed6-8090-474b-914b-775c94066cd8)

**Comment by chriadam** [comment]
I am going to close this bug, since the originally reported issue was fixed.

@mr-manuel can you please file a new bug with some more detail about what precisely the remaining problem is?  Thanks!
