### ISSUE TITLE
Touches not working anymore after scrolling trough a list on iPadOS

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#469]
## Description of the problem
After upgrading to `v0.1.15` I have some issues with the navigation through menus. After the first scrolling through a list (doesnt matter which one, reproducable also on with one element, if you try to scroll anyway) subsequent touches are not recognized anymore. Also touches that are not in the bottom navigation bar are not recognized anymore. If I attach a Bluetooth mouse to the iPad all works normal.

Tested on this devices:
* iPad with iPadOS 16.6 -> not working
* iPad Pro with iPadOS 17.0 -> not working
* iPhone 8 with iOS 16.5.1 -> working
* Samsung Galaxy S20+ with Android 12.0 -> working
* Samsung Galaxy Tab A7 2021 with Android 12 -> working

## How to reproduce
1. Get an iPad and open the GUI with version `v0.1.15` on it.
2. Go to settings and do not scroll yet. Press on any item.
3. Go back and scroll the list. Now you cannot select any item anymore.
4. You can use the bottom navigation bar, but if you go to the overview page for example also the touch on the solar yield do not work anymore.

https://github.com/victronenergy/gui-v2/assets/12592765/5e132e32-438d-4fc5-b8c9-9b6041b7d9e8

**Comment by chriadam** [comment]
Does this still reproduce, now that we're using Qt 6.5.x instead of Qt 6.2.4?

**Comment by mr-manuel** [comment]
Unfortunately the issue is still present. I tested with this buid: https://github.com/victronenergy/gui-v2/actions/runs/7736274314

**Comment by mr-manuel** [comment]
This issue is not apprearing anymore.
