### ISSUE TITLE
Adjust quantity table column widths to avoid eliding quantity values, where possible 

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#479]
Loading the PV inverter page on the local cerbo:

![image](https://github.com/victronenergy/gui-v2/assets/1260099/75a08d06-7ff6-428e-bc07-964f6146fe75)

Would be nice if the energy in the QuantityTableSummary was not elided. Currently the first column has a fixed width, but would be nice to dynamically adjust this.

**Comment by blammit** [comment]
Now looks like this, so it still needs to be fixed.

<img width="912" alt="image" src="https://github.com/victronenergy/gui-v2/assets/1260099/72d8872c-eae4-4a7f-924c-0b0cf24d6e7a">

**Comment by chriadam** [comment]
What is the expected fix?  Change the units so that the number of digits can be reduced?

**Comment by chriadam** [comment]
Adding to 1.0.0 milestone, marking as medium_prio.

**Comment by blammit** [comment]
> What is the expected fix? Change the units so that the number of digits can be reduced?

I would just shrink the width of the L1/L2/L3 column here.

**Comment by DanielMcInnes** [comment]
may be resolved by #620

**Comment by jpetrell** [comment]
After the fix for #620 there is no overlap anymore, but the margin around the energy item is still bit tight so proposing small adjustment: https://github.com/victronenergy/gui-v2/pull/814
