### ISSUE TITLE
Wasm build not working on Mac OS

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#492]
I'm sure I've got something configured incorrectly but not sure what.

I followed the instructions in the Wiki for the WASM build as best I could and got as far as running QtCreator.

I was not sure what to select in the gui-v2 clone for the project but CMakeLists.txt seemed to work.
Yet when I tried to compile, nothing happens. No errors, no outputs.

I have never used QtCreator before so any help would be appreciated.

**Comment by chriadam** [comment]
Closing as resolved :-)
