### ISSUE TITLE
CustomName not displayed for tanks

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#512]
The Tanks page in gui-v2 does not show the tank custom name.

I know some tank sensors like SeeLevel N2K don't allow a custom name to be set locally but that's another issue.

**Comment by chriadam** [comment]
Need feedback from Serj about whether this custom name should be displayed or not, e.g. whether to display instead of the tank type name, or as in addition to the tank type name.  Also, should the custom name be elided if it is too long, etc etc.

**Comment by Serjle** [comment]
<img width="1155" alt="Screenshot 2024-02-07 at 15 13 23" src="https://github.com/victronenergy/gui-v2/assets/119486179/aa63671c-bf2f-4e9b-aa15-16c972a7f028">

**Comment by Serjle** [comment]
If custom name does not fit. We truncate with three dots at the end ... , in settings must be characters limit for custom names

**Comment by kwindrem** [comment]
gui-v1 scrolls long text items. Is this not also a solution for gui-v2?

The mechanism in gui-v1 is Marquee. GuiMods enhanced this to wrap the text. The stock marquee scrolls the text off the left side of the field leaving blank so you have to  wait for it to recycle to see the beginning text.
