### ISSUE TITLE
Display both grid and generator if present in system?

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#519]
More of a question at this point: Will tiles for both AC inputs of a Quattro be displayed? This would be especially useful for showing grid/shore and generator status. If the generator was manually started but the grid is the active input, it would be nice to show the generator's running status. Or if the generator input has priority knowing the grid is now available will help users avoid running the generator unnecessarily.

My ExtTrasnferSwitch package adds two input capability to a Multi and would in the case of grid and generator meters provide status for both sources as well. (It's not clear if I'll be able to migrate my packages to gui-v2 but this is one of the important ones for some system integrators.)

**Comment by mpvader** [comment]
I think they should be, and its being looked into by Serj.

https://victrondevelopment.slack.com/archives/C020QG3JVEW/p1704875985121819

**Comment by jpetrell** [comment]
Duplicate to https://github.com/victronenergy/gui-v2/issues/810?

**Comment by blammit** [comment]
Yes, this is a duplicate. Closing.
