### ISSUE TITLE
No way to return to the original GUI from gui-v2 from remote devices (wasm)

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#523]
The gui-v2 beta notes indicates there is a way to return to the original GUI, but the current gui-v2 Display & Language menu does not have a Standard / Beta GUI selection, so if someone turns on gui-v2 on their system, there's no way back. 

You can reset Settings/Gui/RunningVersion using dbus-spy then restart the gui from the command line but most won't have that capability.

**Comment by chriadam** [comment]
https://github.com/victronenergy/gui-v2/pull/696 adds this feature.
We're fixing some bugs in it currently.  Will close this issue once those bugs are resolved.  Marking as high_prio.

**Comment by DanielMcInnes** [comment]
Fixed elsewhere
