### ISSUE TITLE
Allow left/right swipes to move between main screens

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#538]
Allow the user to swipe between the Brief and Overview page, Overview to Levels etc. to navigate between screens, instead of only doing it by clicking on the nav bar buttons.

Pending design discussions.

**Comment by chriadam** [comment]
Discussed and documented that if we want this feature, it MUST be part of the initial 1.0.0 release.
Awaiting design from Serj.

This is likely to require significant work to implement.

**Comment by chriadam** [comment]
Unblocked, as per https://victrondevelopment.slack.com/archives/C020QG3JVEW/p1706862562071579?thread_ts=1704883226.782939&cid=C020QG3JVEW

**Comment by DanielMcInnes** [comment]
Easier for now to just do the left / right swiping of the main screens
