### ISSUE TITLE
DC System and DC Loads tiles both appear (wasm Cerbo v3.20~26)

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#540]
My system is showing both a DC System and DC Loads tiles:

![Screenshot 2023-11-16 at 8 35 53 AM](https://github.com/victronenergy/gui-v2/assets/58538395/27b35106-b474-4ded-b8b5-64dd945607c3)

I have a SmartShunt set to DC System which goes to my DC load distribution panel.

**Comment by blammit** [comment]
Fixed by https://github.com/victronenergy/gui-v2/pull/565
