### ISSUE TITLE
Workaround for no VRM remote console when running gui-v2

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#544]
As a test, I was able to run gui-v2 on the local display (and also via the wasm web interface) and also run the old GUI in headless mode so it appears in VRM and as venus.local from a local web browser.

I switched to the gui-v2 using the Display & Language menu, then used ssh to set the headless flag file then run /gui/start-gui.sh.

CPU usage is pretty small on the original GUI and I did not notice any performance degradation with both GUIs running.

Not sure if i it makes sense to run the original GUI headless while running gui-v2 locally. It might work around the issue where VRM's remote console currently breaks. because it is trying to connect to the original GUI.

This was on my Cerbo GX btw.

**Comment by mpvader** [comment]
Hi, meanwhile, this been arranged like this:

- there is a setting that allows user to decide which ui runs locally.
- gui-v1 can only be opened in remote console on vrm and on lan when also running locally (see Settings -> Display -> User interface setting).
- gui-v2 can always be opened in remote console on vrm and lan.

In case both are available, then VRM portal shows a chooser to the user.
