### ISSUE TITLE
Can't change inverter mode from drill-down

### ISSUE THREAD

**Issue by kwindrem** [victronenergy/gui-v2#549]
The inverter mode button doen't lead anywhere. I expected a dialog but it does not show up.

Also, I'd prefer to see the mode buttons on the drill-down so you can make the mode change more quickly.

**Comment by chriadam** [comment]
We believe this was fixed recently, can you please check to see whether this issue still exists for you?  Thanks!

**Comment by chriadam** [comment]
Thanks!  Marking as needed for 1.0.0 and medium_prio.

**Comment by blammit** [comment]
Could be the issue fixed by https://github.com/victronenergy/gui-v2/pull/703 ?

**Comment by blammit** [comment]
@kwindrem can you check this with the latest build please?

**Comment by kwindrem** [comment]
The WASM build that is part of v3.30~7 shows the dialog and the On and Off buttons work however the Invert only and Charge only buttons are grayed out. That is the latest I have access to at the moment.

**Comment by blammit** [comment]
@kwindrem what is the value of `/Ac/NumberOfAcInputs` for your device? This should be following the gui-v1 logic, which only allows switching to "Charger only" and "Inverter only" if  `/Ac/NumberOfAcInputs != 0`.

**Comment by blammit** [comment]
Will close this now as it should be addressed. Can re-open later if needed.
