### ISSUE TITLE
Allow switching Brief page circular gauges from percentages to units

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#551]
Matthijs has asked if we could add a setting to allow switching the Brief page circular gauge values from Percentages to being "raw" units (e.g. Battery 87% to Battery 126 AH).

**Comment by chriadam** [comment]
Marking as 1.0.0, medium_prio.

**Comment by DanielMcInnes** [comment]
settings -> Brief View -> ....

**Comment by ReinvdZee** [comment]
This dbus path is already on the dbus: `/Settings/Gui/BriefView/ShowPercentages`. I'm not entirely sure which service is adding this path.

Sounds like this path is supposed to be used for switching between percentages and units. @chriadam, @DanielMcInnes?

**Comment by ReinvdZee** [comment]
@chriadam, @DanielMcInnes,

It turns out that `/Settings/Gui/BriefView/ShowPercentages` is already added by localsettings. This one can be used by `gui-v2`

**Comment by blammit** [comment]
Yes, `/Settings/Gui/BriefView/ShowPercentages` is used to control whether the percentages are shown, but we don't have a setting to control whether it shows percentages as opposed to raw units. 

We could add another setting like `ShowRawValues` or maybe use a different setting altogether like `TankUnits` and use that to control all three possibilities, e.g. 0 = do not show percentage or raw units, 1 = show percentage, 2 = show raw unit value. @ReinvdZee what do you think?

**Comment by ReinvdZee** [comment]
@blammit,

> e.g. 0 = do not show percentage or raw units

So there is supposed to be an option to show nothing? Or not show any unit (just numbers)? 

If there are three options, and they are always exclusive, then I would propose using one path (can be `/Settings/Gui/BriefView/ShowPercentages`) with 3 options.

**Comment by blammit** [comment]
> @blammit,
> 
> > e.g. 0 = do not show percentage or raw units
> 
> So there is supposed to be an option to show nothing? Or not show any unit (just numbers)?

Currently it is used as either true/false, so true = show %, and false = show nothing.

> 
> If there are three options, and they are always exclusive, then I would propose using one path (can be `/Settings/Gui/BriefView/ShowPercentages`) with 3 options.

My initial thought was that a name like `ShowPercentages` doesn't indicate a 3-option value, but looking at it again, it seems fine to use it in this manner. Sounds good to me.

**Comment by ReinvdZee** [comment]
>Currently it is used as either true/false, so true = show %, and false = show nothing.

Would one actually prefer to have the brief page show "nothing"? What unit will the displayed number be in then? 

Afaic, the only useful options are to show the values in percentages (`ShowPercentages` = true), or to show absolute units (`ShowPercentages` = false).

**Comment by blammit** [comment]
> Would one actually prefer to have the brief page show "nothing"? What unit will the displayed number be in then?

Currently if you set `ShowPercentages = false`, then it will just show the tank name. E.g. just "battery", "Freshwater" etc. in the screenshot above.

**Comment by ReinvdZee** [comment]
>Currently if you set ShowPercentages = false, then it will just show the tank name. E.g. just "battery", "Freshwater" etc. in the screenshot above.


Understood, then it makes sense to have 3 options. I would propose to rename `/Settings/Gui/BriefView/ShowPercentages` to `/Settings/Gui/BriefView/Unit` and let it have the options 0 ("none"), 1 ("absolute") and 2 ("percentage")

**Comment by blammit** [comment]
> > Currently if you set ShowPercentages = false, then it will just show the tank name. E.g. just "battery", "Freshwater" etc. in the screenshot above.
> 
> Understood, then it makes sense to have 3 options. I would propose to rename `/Settings/Gui/BriefView/ShowPercentages` to `/Settings/Gui/BriefView/Unit` and let it have the options 0 ("none"), 1 ("absolute") and 2 ("percentage")

Sounds good to me. Can gui-v2 use it like this already, or is `ShowPercentages` currently limited with a maximum value of 1?

**Comment by ReinvdZee** [comment]
@blammit, Currently, `ShowPercentages` has a maximum of 1. 

If there are no objections I'll remove `/Settings/Gui/BriefView/ShowPercentages` and add `/Settings/Gui/BriefView/Unit` with a maximum of 2.

@jhofstee, @mpvader?

**Comment by mpvader** [comment]
Ok

**Comment by jpetrell** [comment]
> - 1: show value in absolute units
> Default value is set to 1

Sorry just to verify do we want to change the default from percentages to absolute unit values? I don't have preferences either way, just the original issue description talks about adding a setting to allow switching from percentages to "raw" units, not the other way around.
