### ISSUE TITLE
Ensure Inverter/Charger details are also fetched for non-vebus services

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#561]
The details for the Inverter/Charger box on the Overview page should come from one of the following:

- com.victronenergy.vebus 
- com.victronenergy.multi (Multi RS)
- com.victronenergy.inverter (Inverter RS and Phoenix Inverter, which do not have AC inputs)

These are ordered by preference, i.e. pick vebus if available, otherwise pick a Multi RS, otherwise an inverter. If there is more than service for a particular type, use the one with the lowest device instance.

Currently, inverters are not considered, only vebus/multi devices. So, in terms of implementation changes: 
- VeBusDevicesImpl.qml for dbus/mqtt backends already include the vebus and multi services, just need to support `inverter` services as well.
- If `inverter` services are added to Global.veBusDevices.model as per the previous point, perhaps we don't need a separate Global.inverters (and the associated dbus/mqtt/mock backend wrappers)? Global.inverters.model is only used in the Device List at present, and the Device List already includes the contents of Global.veBusDevices.model. 

In terms of user-visible changes, if there are no vebus/multi devices on the system, but there is an inverter device, then:

- If you click on Inverter/Charger, you will see the details for the inverter (similar to what you get from the Device List details for the inverter)
- The inverter appears in the control cards

(This can be tested with venus-docker simulation 'h', for example.)

**Comment by chriadam** [comment]
Needed for 1.0.0, and high priority.  Marking as high_prio.

**Comment by blammit** [comment]
The user-visible effects of these changes are that if there are no vebus/multi devices on the system, but there is an inverter device, then:

- If you click on Inverter/Charger, you will see the details for the inverter (similar to what you get from the Device List details for the inverter)
- The inverter appears in the control cards

This can be tested with venus-docker simulation 'h', for example.

**Comment by mpvader** [comment]
Hey @blammit or @DanielMcInnes , what data on the screen is this about? Can you share a screenshot?

**Comment by blammit** [comment]
> Hey @blammit or @DanielMcInnes , what data on the screen is this about? Can you share a screenshot?

This is mainly regarding the Inverter/Charger overview box. Clicking on it should show the `inverter` details, if there are no `vebus` or `multi` devices:

<img width="569" alt="image" src="https://github.com/victronenergy/gui-v2/assets/1260099/587b3c64-7996-41c5-a5b3-d7705221b90c">

For consistency, I added a card to the control cards for the inverter, like the ones for vebus/multi devices, but without the input current limit, i.e. like the one below (except this is for the vebus device, with an input current limit):

<img width="459" alt="image" src="https://github.com/victronenergy/gui-v2/assets/1260099/12750f0d-ca21-4fc7-be09-c6e918eaf822">

**Comment by mpvader** [comment]
Ok thank you. Clicking on it should show a list of all such devices. Not just one. Is that clear?

**Comment by blammit** [comment]
> Ok thank you. Clicking on it should show a list of all such devices. Not just one. Is that clear?

Sure, the original spec was to just show the details for the "first" device, but it would be simple to show a list instead. Which main details would it show for each inverter/charger in the list? I suppose just the "state" and the "mode" for each inverter/charger will do?

**Comment by blammit** [comment]
Actually, maybe only the "state" would be better, as that text can be quite long.
