### ISSUE TITLE
Charfging-station spelling mistake

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#572]
![image](https://github.com/victronenergy/gui-v2/assets/5200296/48fd06f6-ec39-4dad-aaff-934629d83f7f)

**Comment by blammit** [comment]
@mpvader This string isn't created in the gui-v2 app layer;  assuming no /CustomName has been set, this string is coming from the com.victronenergy.evcharger/ProductName, so the bug is wherever that text is produced.

**Comment by mpvader** [comment]
Ok!
