### ISSUE TITLE
Screen Sleep function / feature

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#583]
See https://victrondevelopment.slack.com/archives/C020QG3JVEW/p1701166638589059

Add a new button to the top-right of the brief page (actually the status bar) which puts the screen to sleep (not just black, but turn off backlight).  This allows people to go to sleep if their unit is in a caravan etc.

Needs support from venus-platform for hardware hooks (display on/off) if that doesn't exist already.

Once a screen is asleep, any touch input on the screen should wake it up again.

**Comment by blammit** [comment]
> Needs support from venus-platform for hardware hooks (display on/off) if that doesn't exist already.

Doesn't exist yet; marking this task as blocked. Will need something like the screen-blanking and wake-up features in gui-v1 (implemented by VePlatform/VePlatformVenus).

**Comment by blammit** [comment]
Discussed with Mathijs, this feature shoudn't need to be in venus-platform. We can implement this according to whatever gui-v1 does, and put the implementation in gui-v2, or implement in venus-platform if needed.

Note: the sleep button shouldn't appear in wasm builds as we cannot turn the display/backlight off there. It should only appear in device builds.

**Comment by chriadam** [comment]
Marking as high priority.

**Comment by mpvader** [comment]
Lets move this one out of v1.0.0. Its oone of the urgent things after first release, but should definitively not block it.
