### ISSUE TITLE
Show modal dialog when device is rebooted

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#604]
In Settings > General, when "Reboot now" is clicked, show a modal dialog to prevent interaction with the UI while the reboot is in progress.

**Comment by kwindrem** [comment]
In GUI v1, tapping on Reboot triggers the reboot process. I've done it by accident more than once. Of course a reboot isn't damaging but does take the system down for a few minutes.

It might be nice to present an "are you sure?" dialog requiring a second tap on a Reboot button or allow a Cancel.

**Comment by blammit** [comment]
Agreed, this can show a dialog with OK/Cancel buttons.
