### ISSUE TITLE
Device List: com.victronenergy.genset.xxx Mode sub-page issue

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/gui-v2#605]
On the `com.victronenergy.genset.xxx` device list item, the `Modes` sub-page is empty, so that the mode cannot neither be viewed nor changed.

![172 30 30 120_gui-beta_(Ekrano GX) (3)](https://github.com/victronenergy/gui-v2/assets/11627598/60f6f6bd-f068-4cde-aa81-919feb2013e0)
![172 30 30 120_ (1)](https://github.com/victronenergy/gui-v2/assets/11627598/0661de62-a427-470d-92b8-d44682a20b49)

**Comment by blammit** [comment]
Thanks for reporting, will be fixed by https://github.com/victronenergy/gui-v2/pull/626
