### ISSUE TITLE
Device List: com.victronenergy.genset.xxx state issue

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/gui-v2#606]
On the `com.victronenergy.genset.xxx` device list item, the `Status` value is translated/mapped incorrectly.

![172 30 30 120_gui-beta_(Ekrano GX) (2)](https://github.com/victronenergy/gui-v2/assets/11627598/eee550ae-814c-4bba-9136-ce661f40cb1f)
![172 30 30 120_](https://github.com/victronenergy/gui-v2/assets/11627598/0cf94cc3-a270-4c3b-b81d-91dd634a8485)

**Comment by philipptrenz** [comment]
Correct mapping is documented at https://github.com/victronenergy/venus/wiki/dbus#generator-data

```
/StatusCode                 <- 0=Standby; 1..7=Startup; 8=Running; 9=Stopping; 10=Error
```

**Comment by blammit** [comment]
Thanks for reporting, will be fixed by https://github.com/victronenergy/gui-v2/pull/626
