### ISSUE TITLE
Device List: com.victronenergy.genset.xxx Auto start/stop sub-pages missing

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/gui-v2#607]
On the `com.victronenergy.genset.xxx` device list item, the `Auto start/stop` sub-page item is missing. This might be related to #605, as on the old gui the menu item was only shown when mode `Auto start/stop` was selected. 

I would highly suggest that the `Auto start/stop` menu item should be permanently displayed, regardless of the selected mode. Disappearing menu items are somewhat confusing, especially to configuration pages.

![172 30 30 120_gui-beta_(Ekrano GX) (4)](https://github.com/victronenergy/gui-v2/assets/11627598/b5187f08-5c53-4503-bebb-5212a4ea7826)
![172 30 30 120_ (2)](https://github.com/victronenergy/gui-v2/assets/11627598/57132022-a09b-494a-8f50-42032870150b)

**Comment by blammit** [comment]
Thanks for reporting, will be fixed by https://github.com/victronenergy/gui-v2/pull/626
