### ISSUE TITLE
Device List: com.victronenergy.genset.xxx Speed value on Engine sub-page is missing its unit

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/gui-v2#608]
On the `com.victronenergy.genset.xxx` device list item at the `Engine` sub-page, the `Speed` value is missing its unit (RPM).

![172 30 30 120_gui-beta_(Ekrano GX) (1)](https://github.com/victronenergy/gui-v2/assets/11627598/44c458c6-d738-4f24-99e6-f0d853d3260f)

**Comment by blammit** [comment]
Thanks for reporting, will be fixed by https://github.com/victronenergy/gui-v2/pull/626
