### ISSUE TITLE
Usage from grid off by factor 10?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#611]
https://community.victronenergy.com/questions/249509/venus-os-v32034-available-for-testing.html

![IMG_0708](https://github.com/victronenergy/gui-v2/assets/5200296/44eaddab-4f68-4baf-89f7-ff5317bf6664)

**Comment by DanielMcInnes** [comment]
I can't easily reproduce this, I see the following:
![Screenshot from 2023-12-18 11-44-09](https://github.com/victronenergy/gui-v2/assets/6416318/10af722d-871e-44c3-b8a3-590da9629954)
![Screenshot from 2023-12-18 11-44-16](https://github.com/victronenergy/gui-v2/assets/6416318/df392437-5db1-49f3-a214-5d3b40617010)

**Comment by DanielMcInnes** [comment]
I can reproduce this now, it happens when we go over 9999W

**Comment by chriadam** [comment]
Possibly a bug in my recent Units.js to .cpp conversion?
