### ISSUE TITLE
Device List: Battery page issues

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#614]
## Details page

1. The cell ID's, which are strings, are not shown.
2. The voltage has only one decimal instead of three.
3. The unit is missing for the capacity

![grafik](https://github.com/victronenergy/gui-v2/assets/12592765/45824a00-cf15-4b6d-bb82-90b62bf02f9c)

## Device page

![grafik](https://github.com/victronenergy/gui-v2/assets/12592765/34f70ffc-570c-4b5e-aabb-6d374170bcc4)

I will fix the errors by opening a PR.

**Comment by mr-manuel** [comment]
@mpvader has the firmware always to be a hex number? If yes, then I have to change the versioning format of all my add-ons :-)

https://github.com/victronenergy/gui-v2/blob/8e57400d3fc631aa55f794cbd0cd62ae1ab29a1d/components/settings/ListFirmwareVersionItem.qml#L28-L40

I searched FirmwareVersion on https://github.com/victronenergy/venus/wiki/dbus-api and it says that it can be a string or did I missunderstood that?

> /FirmwareVersion
> GetText: A string, containing the firmware version which is formatted equal as used in change logs of the product, and/or on labels etcetera. This string is also what the Venus GUI and VRM portal will show to users.
> 
> GetValue: Numeric representation of the firmware version. To be prepared for automatic firmware updates, make sure that the numeric value is such that a newer version leads to a higher number. And also that the number is in the same format in the firmware update files (if available for this product); so that when indexed in a library, the number can be used to check up-to-dateness of the product. All downstream software will not, and may not, format this number itself for showing the user. Instead it must use the string as returned by GetText.

**Comment by mr-manuel** [comment]
It it's ok, I would change

https://github.com/victronenergy/gui-v2/blob/8e57400d3fc631aa55f794cbd0cd62ae1ab29a1d/components/settings/ListFirmwareVersionItem.qml#L30-L31

to

```qml
		// Return the version as it is, if format is "vebus" or if the version is not a hex number
		if (format === "vebus" || !version.match(/^[0-9A-F]+$/i))
			return "v" + hexString;
```

**Comment by mr-manuel** [comment]
With #616 I nearly resolved all problems. There are two problems left, that I was not able to solve.

1. Cell voltage shows only one decimal instead of three
2. The cell ID's for `minVoltageCellId`, `maxVoltageCellId`, `minTemperatureCellId` and `maxTemperatureCellId` are not shown, even if they are present on the debug page.
    ![venus-os-ruuvi-tag](https://github.com/victronenergy/gui-v2/assets/12592765/db0c0ee1-2e40-4105-90bd-970866a6b198)

@blammit could you check that?

**Comment by blammit** [comment]
Sure, will look into the cell IDs issue next week. I also have an upcoming PR that will address the decimal issue.

**Comment by mr-manuel** [comment]
> Sure, will look into the cell IDs issue next week. I also have an upcoming PR that will address the decimal issue.

Any news for this?

**Comment by blammit** [comment]
Sorry, I forgot about this last week. Will definitely take a look this week and let you know.

**Comment by blammit** [comment]
@mr-manuel can you see whether https://github.com/victronenergy/gui-v2/pull/698 fixes the issue?

**Comment by mr-manuel** [comment]
Looks good now!

![grafik](https://github.com/victronenergy/gui-v2/assets/12592765/ac04a924-433a-4eca-a917-438ea4012373)

**Comment by blammit** [comment]
Great, thank you -- will close as fixed.
