### ISSUE TITLE
Battery percentage is unnecessarily elided in Brief and Overview pages

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#636]
I'm seeing this when the battery charge is 100%. Noticed it with the browser/wasm, so it's possible it only happens in 7" screen size:

![image](https://github.com/victronenergy/gui-v2/assets/1260099/8435772f-a200-4f8d-8cf3-7f2903e6825a)

![image](https://github.com/victronenergy/gui-v2/assets/1260099/d64189fe-239e-4248-9ad7-32d6e79bb1ac)

**Comment by chriadam** [comment]
Ouch, thanks.

Serj has asked that we investigate the possibility of generating fixed-width bitmaps / pre-rendered images for each of the (horizontally-centered) digits rendered in the required font + font colour as specified by the theme (and font pixel size required for every label).

I was thinking it might be implemented via a QQuickImageProvider using query parameters to define font / pixelSize / color, which can render on first access then populate a cache...?

**Comment by chriadam** [comment]
See #588 for the "proper" fix path, but for now I've created temporary fix in #659.

**Comment by chriadam** [comment]
Bea fixed this properly in https://github.com/victronenergy/gui-v2/pull/671
Closing as done.
