### ISSUE TITLE
Overview page: EV Charger shows incomplete power data

### ISSUE THREAD

**Issue by mr-manuel** [victronenergy/gui-v2#637]
On the overview page the current power of the EV Charger displays the second last value and not the current one. Is this intended?

In the detailed page it is correct.

![guiv2_ev-charger](https://github.com/victronenergy/gui-v2/assets/12592765/b3f7ae1f-9b69-43e7-b0f2-21ba323d7fe7)

**Comment by chriadam** [comment]
Looks like a clear bug to me - thanks for reporting!
