### ISSUE TITLE
Issue with the Ruuvis

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#649]
Dirk-Jan will look into reproducing this. 

<img width="469" alt="image" src="https://github.com/victronenergy/gui-v2/assets/5200296/40832928-75d4-410c-b2d6-13b4ef552dcd">

https://community.victronenergy.com/questions/249509/venus-os-v32034-available-for-testing.html

**Comment by blammit** [comment]
Might be the same as https://github.com/victronenergy/gui-v2/issues/511 ? In which case would be fixed by https://github.com/victronenergy/gui-v2/pull/658

**Comment by dirkjanfaber** [comment]
Yes, you are right. That is the same issue. Closing this as a duplicate from #511 .
