### ISSUE TITLE
SmartShunt configured as DC system issues

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#651]
### Plan:

To start, @ReinvdZee will look into reproducing this. The person that can tell you how systems using SmartShunts configured for DC system should work exactly is Izak; if you need help, please ask him in the #venus channel (not one on one). And read this section in the manual: https://www.victronenergy.com/media/pg/Cerbo_GX/en/connecting-victron-products.html#UUID-4698338e-674e-1d34-c091-498f031a332c   (4.3.1. DC load monitor mode).

### Report:

https://community.victronenergy.com/questions/249509/venus-os-v32034-available-for-testing.html

<img width="599" alt="image" src="https://github.com/victronenergy/gui-v2/assets/5200296/6173d8e2-cc52-45be-93b7-c84b96bb9439">

ps. the other reported issue by him, not included in the screenshot, will be looked at in due time, I'm purposefully ignoring that for now, since we don't support Shelly meters officially.

**Comment by blammit** [comment]
I can reproduce this. Have made a fix for this here: https://github.com/victronenergy/gui-v2/pull/660
