### ISSUE TITLE
Device List: com.victronenergy.genset.xxx Run time and service values not editable

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/gui-v2#666]
At _Auto start/stop_ > _Settings_ > _Run time and service_, the values for "Generator total runtime (hours)" and "Generator service interval (hours)" seem to be not editable. Got a blinking cursor, but no popup and not keyboard editable.
Tested with v3.20~37 (WASM).

**Comment by blammit** [comment]
This is broken due to https://github.com/victronenergy/gui-v2/issues/677.
