### ISSUE TITLE
Generator control card: enabling auto start doesn't work?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#682]
Reported by a user, see 2nd screenshot, and I can also reproduce this myself.

Note that (a) when doing the same (enabling autostart) from the Settings menu, all works fine. Clicking the toggle switch in gui-v2 (WASM) immediately makes for the toggle to switch in Remote Console (old gui) as well. and (b) disabling does work well.

The fault state:

![image](https://github.com/victronenergy/gui-v2/assets/5200296/c9220bad-cca1-4829-96e9-f27b59c5d0c2)

The report by the user:
![image](https://github.com/victronenergy/gui-v2/assets/5200296/aa36d4ea-6fba-4322-a1bf-389025edef65)

https://community.victronenergy.com/questions/249509/venus-os-v32034-available-for-testing.html?page=2&pageSize=50&sort=oldest

**Comment by DanielMcInnes** [comment]
M.V can reproduce, so ask him if you can't

**Comment by jpetrell** [comment]
Fix PR https://github.com/victronenergy/gui-v2/pull/719

**Comment by mpvader** [comment]
This one can / should’ve been closed?

**Comment by ReinvdZee** [comment]
@jpetrell, @mpvader,

I am still able to reproduce this issue on V3.30~7, running gui-v2 v0.2.10 (afaict this PR is merged in this version).

![image](https://github.com/victronenergy/gui-v2/assets/38864570/d1a09a7a-347d-488f-8690-8777eded4633)


When controlling the autostart functionality from gui-v1, the control card in gui-v2 is not following properly:
![image](https://github.com/victronenergy/gui-v2/assets/38864570/28dda870-8c54-41f3-bb5a-d8cd8b8ec575)

The autostart switch on gui-v2 can be either on or off. dbus path `Settings/Generator0/AutoStartEnabled` correctly follows gui-v1.

**Comment by jpetrell** [comment]
> I am still able to reproduce this issue

Earlier PR fixed enabling autostart from the generator control card, but after the PR the switch no longer updated if the autostart value changed elsewhere. Should be fixed now in https://github.com/victronenergy/gui-v2/pull/812.
