### ISSUE TITLE
PV Inverter details - position doesn't work well?

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#683]
See below screenshot for detalis. In case you want to test this somewhere on a live system, ask Izak.

![image](https://github.com/victronenergy/gui-v2/assets/5200296/1d4a6ff6-b1b4-40d8-a039-af3ce840d748)

from : https://community.victronenergy.com/questions/249509/venus-os-v32034-available-for-testing.html?page=2&pageSize=50&sort=oldest

**Comment by blammit** [comment]
This was just fixed recently, in 2f1c5d6653db76fd567b4ba22183fb007d1a4756
