### ISSUE TITLE
Bug in ListFirmwareVersionItem

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#711]
To reproduce: 
Overview Page -> click 'inverter / charger' to open drill down -> Product Page -> Device

qrc:/qt/qml/Victron/VenusOS/components/settings/ListFirmwareVersionItem.qml:31: TypeError: Property 'match' of object 1058 is not a function

@mr-manuel fyi

**Comment by mr-manuel** [comment]
With the latest version this indeed do not work anymore. Could this be a Qt bug?
