### ISSUE TITLE
Implement weather fallback

### ISSUE THREAD

**Issue by DanielMcInnes** [victronenergy/gui-v2#717]
As discussed in the meeting today, @jepefe will talk to Serj about implementing a fallback design. And in v1.0.0 release we'll go for that.

Two reasons: making this work requires discussion + work outside of gui-v2; and we need a fallback anyway for systems that don't have internet.

**Comment by mpvader** [comment]
Hi @kwindrem we could do that, but first we're just going to implement a fallback. It needs to work well out of the box without requiring temperature sensors or user configuration.

**Comment by mpvader** [comment]
A design has been made and approved. (see Serj for figma files and such).

<img width="1256" alt="image" src="https://github.com/victronenergy/gui-v2/assets/5200296/235efd01-5cd2-4aa9-a6f6-271b04b7eece">
