### ISSUE TITLE
Reword online feed entries

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#725]
In gui-v1 we've already reworded them, same needs doing for gui-v2.

It was done in two commits:

https://github.com/victronenergy/gui/commit/1c8f59e8db844a775288b0607ebfe77ed3f7cb21

and this small after thought:
https://github.com/victronenergy/gui/commit/de0b8cefbb16cbb657b8cdc50057619a8aac7ad5

**Comment by jpetrell** [comment]
PR https://github.com/victronenergy/gui-v2/pull/729

**Comment by jpetrell** [comment]
Fixed.
