### ISSUE TITLE
Device List: com.victronenergy.genset.xxx Start/Stop toast text is inverted

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/gui-v2#736]
The text strings in the toasts/popups are inverted: When starting the genset, it shows "Stopping, ..." and "Starting, ..." when toggled to stop.

![started](https://github.com/victronenergy/gui-v2/assets/11627598/9f7cba33-6f51-4373-a1ca-b4c1b69b77a2)
![stopped](https://github.com/victronenergy/gui-v2/assets/11627598/ea20cebe-e5ba-4b19-bfc2-d43670c3e25d)

**Comment by blammit** [comment]
@jpetrell did you fix this recently already?
