### ISSUE TITLE
Device List: com.victronenergy.genset.xxx Engine parameter inconsistencies

### ISSUE THREAD

**Issue by philipptrenz** [victronenergy/gui-v2#737]
I found some inconsistencies regarding generator engine parameters:
- Load should be displayed rounded without a decimal place
- Load unit "%" is missing
- Oil pressure unit "kPA" is missing
- Coolant temperature unit should be "°C" instead of "°"
- Coolant temperature should be displayed rounded without a decimal place

<img width="483" alt="generator_engine_values_gui-v1" src="https://github.com/victronenergy/gui-v2/assets/11627598/e9a5a44c-5e96-482d-8c46-e4bb8208c0f7">
<img width="483" alt="generator_engine_values_gui-v2" src="https://github.com/victronenergy/gui-v2/assets/11627598/eac1fe0c-1535-49b8-8fca-e651a02f237a">

**Comment by philipptrenz** [comment]
Furthermore, I want to propose two changes that go beyond gui-v1:
- Adding the `/Engine/OilTemperature` dbus path element, unit "°C", rounded to no decimal place
- Changing "Operating time" formatting to always display in hours

I have been asked the latter several times by customers; a unit other than hours is not typical for generators.

**Comment by blammit** [comment]
@jepefe could you comment on the `/Engine/OilTemperature` and "Operating time" suggestions please?

Also, in gui-v2 the Overview page and Levels pages just show the degrees symbol, e.g. "15°" instead of "15°C", and this formatting extends to the settings pages as well. Is this okay, or should it show the longer "15°C" form in the settings pages, to be consistent with gui-v1?

**Comment by jepefe** [comment]
@blammit 
The full unit must be shown so "15°C" everywhere and for this page the decimal can be removed.
Operating time can be displayed in hours instead of formatted time string. This is probably more convenient for operators.

**Comment by blammit** [comment]
@jepefe thanks, and what about adding `/Engine/OilTemperature` as Philipp suggested?

**Comment by philipptrenz** [comment]
I can add it to gui-v1, although I think it is not worth a back port and thus will be released not before v3.3 – when v1 has maybe already been replaced by v2.

**Comment by jepefe** [comment]
@blammit 
It can be added, make it show conditionally when the reading is available.

**Comment by blammit** [comment]
> Furthermore, I want to propose two changes that go beyond gui-v1:
> 
> * Adding the `/Engine/OilTemperature` dbus path element, unit "°C", rounded to no decimal place
> * Changing "Operating time" formatting to always display in hours
> 
> I have been asked the latter several times by customers; a unit other than hours is not typical for generators.

@philipptrenz if displaying the operating time in hours, should it be displayed as "hh:mm" if there are minutes? Or what would you suggest?

**Comment by philipptrenz** [comment]
@blammit I also asked myself the same question before. I guess a higher resolution does not hurt, so I would opt for `XXXh YYm`

**Comment by blammit** [comment]
Fixed by https://github.com/victronenergy/gui-v2/pull/830
