### ISSUE TITLE
Use visual indications on Brief page for negative AC input values

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#747]
Add the ">" and "<" icons on the Brief page between the AC input icon and the power/current value, when "ESS feedback to grid" is enabled. See Figma design.

"ESS feedback to grid" is considered true when:

- com.victronenergy.system/Hub == 4
- /Settings/CGwacs/OvervoltageFeedIn == 1
- /Settings/CGwacs/PreventFeedback == 0

**Comment by jpetrell** [comment]
The indication seems really useful thing to add, but visually it is bit of a shame to lose the horizontal alignment of the quantity labels between the top and bottom gauges.

![image](https://github.com/victronenergy/gui-v2/assets/2203667/fcd57466-e2e8-4ba6-a597-5ae0ce83ed8c)
