### ISSUE TITLE
Add status LED enable/disable switch

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#749]
This setting was recently added to gui-v1. 

To let Cerbo users disable the status LEDs in the casing, this option was added to the general settings page:

```
MbSwitch {
	name: qsTr("Enable status LEDs")
	bind: Utils.path(bindPrefix, "/Settings/LEDs/Enable")
	show: item.valid
}
```

This option should be added to gui-v2 as well.

**Comment by jpetrell** [comment]
Draft PR https://github.com/victronenergy/gui-v2/pull/763

Needs testing still, so far I have been using Ekrano GX, seems I need to set up Cerbo now since the setting was added to "to let Cerbo users disable the status LEDs in the casing".
