### ISSUE TITLE
DcDc converter page: small changes

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#752]
Please mirror the changes from gui-v1: 
https://github.com/victronenergy/gui/commit/894cc2a7a842253fc4fc3161740b2710b39d309d

**Comment by jpetrell** [comment]
AFAICS There is no DcDcConverter.qml equivalent yet in gui v2? Task #738 includes an item about adding support for .dcdc services with input and output details.

**Comment by ReinvdZee** [comment]
@jpetrell, when solving that issue, the minor changes of this issue will be included as well. 
Closing this one.
