### ISSUE TITLE
Update firmware feed terms

### ISSUE THREAD

**Issue by ReinvdZee** [victronenergy/gui-v2#753]
Update the "update feed" terms to:
 
- "Latest release" -> "Official release"
- "Latest release candidate" -> "Beta release (candidate)"
- "Testing" -> "Testing (Victron internal)"
- "Develop" -> "Develop (Victron internal)"

See also:
https://github.com/victronenergy/gui/commit/1c8f59e8db844a775288b0607ebfe77ed3f7cb21

**Comment by jpetrell** [comment]
Duplicate to https://github.com/victronenergy/gui-v2/issues/725 , fixed in https://github.com/victronenergy/gui-v2/pull/729.

**Comment by ReinvdZee** [comment]
Alright, closing.
