### ISSUE TITLE
When set to Amps, certain readings keep increasing

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#777]
Reported here: https://community.victronenergy.com/questions/262520/venus-os-v3304-available-for-testing.html

![image](https://github.com/victronenergy/gui-v2/assets/5200296/6222cb74-781a-41ef-9405-5b6557d9a855)

![image](https://github.com/victronenergy/gui-v2/assets/5200296/565660f6-65b2-4111-b339-8e95860e8205)

**Comment by jpetrell** [comment]
The Brief page gets the amps from a component called `SystemAc`, which calls the amps "total current" of an one-phase system. Whenever either `"/Ac/ConsumptionOnInput/L[n]/Current"` or `"/Ac/ConsumptionOnOutput/L[n]/Current"` values update the `SystemAc`'s current property gets updated by summing up the existing current with the updated currents.

It is easy to disable the accumulation, but I don't really understand what exactly is the correct behavior:

```
data/SystemAc.qml
-    _firstPhaseCurrent = Units.sumRealNumbers(_firstPhaseCurrent, data.current)
+    _firstPhaseCurrent = data.current
```

Will sync tomorrow with Rein.

**Comment by kwindrem** [comment]
I recall a recent discussion on this subject and agree that currents should no be summed across multiple phases. The only valid information is individual leg currents so these need to be shown separately as a numeric value and where gauges are used, as multiple bars on the gauge.

Summing currents implies that somehow the maximum allowed current is the sum of the maximums of all the phases when in fact there is no such limit. A potential overload can potentially be hidden by looking at a summed current if one leg's current is substantially larger than the others.

**Comment by ReinvdZee** [comment]
@jpetrell, 

The top right gauge displays the value of `Ac/ConsumptionOnOutput/L1/Current`. This is also mentioned [here](https://github.com/victronenergy/venus/issues/1217#issuecomment-1961670898)

@jepefe, @izak, can you confirm?
