### ISSUE TITLE
Generator and Grid/Shore overview boxes should be visible at the same time

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#810]
Run venus-docker simulation "o". 

Observe on the Overview page that the left-handed box is often missing. Sometimes it will appear as "Shore" when the shore AC input is connected, other times as "Generator" when the generator is connected, then it will disappear occasionally. 

~However, as per the design, if the grid/shore is not connected but a generator is present, the generator box should still be shown (even if it is not running/connected). In those cases, it can just show "Stopped" as the generator status.~

Updated: both the grid/shore and generator boxes should be visible at the same time. See updated design.

**Comment by blammit** [comment]
The generator box disappears because Connected=0 so gui-v2 assumes it should not be displayed in this case. But I think in this case it should be displayed anyway, to avoid having the empty space on the left hand side.

**Comment by mpvader** [comment]
discussed in design meeting a while ago, making sure we finalise it here: https://victrondevelopment.slack.com/archives/C020QG3JVEW/p1709109365057129

**Comment by blammit** [comment]
Design as been finalized. See "Solution A - Scale down font size" in slack discussion.

**Comment by jpetrell** [comment]
Discussed with Serj that this may require touching the box size or paddings. When making the necessary modifications would maybe be good to fix some of the existing padding issues #730 at the same go.
