### ISSUE TITLE
gui-v2 / MQTT on LAN security

### ISSUE THREAD

**Issue by mpvader** [victronenergy/gui-v2#811]
Waits for work in Venus OS: https://github.com/victronenergy/venus-private/issues/330

**Comment by jpetrell** [comment]
Security wizard in gui-v1:
![image](https://github.com/victronenergy/gui-v2/assets/2203667/afde489e-0160-4558-b152-89cc38136f26)

**Comment by jpetrell** [comment]
Pending completion of inclusion of the enablers in the Venus platform.

**Comment by chriadam** [comment]
This has been merged to main.  Closing as fixed.
