### ISSUE TITLE
Show Celsius/Fahrenheit abbreviation where temperatures are shown

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#829]
Discussed with @jepefe in https://github.com/victronenergy/gui-v2/issues/737 and in the Figma designs that for disambiguation, gui-v2 should show `°C` and `°F` everywhere that temperatures are shown, instead of just the `°` degrees symbol. 

The exception is in the environment gauges: "C" and "F" are already shown at the top of the temperature gauge, so the bottom temperature value does not need to show the full `°C` or `°F` value (and there is not enough space there anyway).

**Comment by jpetrell** [comment]
> The exception is in the environment gauges: "C" and "F" are already shown at the top of the temperature gauge, so the bottom temperature value does not need to show the full °C or °F value (and there is not enough space there anyway).

I raised the issue earlier that while the bottom part already shows degree (which I didn't initially notice) seeing "C" without the degree felt confusing so agreed to add degree there (which I did in the environment gauge design update). The official symbol of Celsius is °C, not C.
