### ISSUE TITLE
Display off timer is not yet implemented

### ISSUE THREAD

**Issue by jhofstee** [victronenergy/gui-v2#838]
In the display & language menu there is a option to set the display off time. This is only relevant for the ARM version, not the wasm one. Currently it is not implemented in gui-v2 though. Since handling this over dbus / MQTT is not necessary and only introduces unwanted delays and traffic, it can simply be done by writing a 1 or 0 to the file as found in the config file /etc/venus/blank_display_device. The file will not be there if the display cannot be blanked. Any touch event should unblank the screen, the event itself should be ignored; e.g. it should not enter a submenu etc.

**Comment by jpetrell** [comment]
Sorry missed this earlier. Fixed in a separate issue #859.
