### ISSUE TITLE
Don't display the #0 error code when there is no error

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#864]
Some error items show "No error" (Generator start/stop), others "#0 No error" (Orion XS device settings), which feels techy. Error codes are in use to make errors identifieable and less ambiguous, but they are only relevant for when there is an error. In most cases I would expect devices to not be in the error state so hopefully you only see the error codes when there is an actual issue to react to.

**Comment by blammit** [comment]
Currently aligns with gui-v1 behaviour, will change where necessary.
