### ISSUE TITLE
Fix tank level fallback calculation for top-down tank level sensors

### ISSUE THREAD

**Issue by chriadam** [victronenergy/gui-v2#937]
Most tank sensors are "float" based, and they effectively measure the amount of liquid in the tank and report that as the "remaining" value.

Some newer tank sensors are ultrasonic, and they can measure either from the bottom-up (i.e. measuring the amount of liquid in the tank) or they can measure from the top-down (i.e. measuring the amount of air in the tank).  In either case, the measured value is reported as the "remaining" value.  For top-down tanks, there should be an "inverted" bit which is set, to let the system know that the "remaining" value should be inverted as the measurement is of the AIR and not the LIQUID in the tank.

In many cases, this never poses a "real" problem for gui-v2, as the tank device will have a "level" value which is exposed on DBus/MQTT.  This "level" value appears to be correct for (at least some) top-down tanks we have encountered (see e.g. issue #680) and so we can use that value directly and ignore the "remaining" value.

However, it is possible that some tank device will expose the "remaining" value and NOT a valid "level" value, in which case gui-v2 has an algorithm to derive the "level" of the tank from its "capacity" and "remaining" values.  When we need to perform this derivation, gui-v2 will also need to know whether or not it needs to "invert" the "remaining" value when calculating the "level" value - but currently this "invert" bit isn't exposed to gui-v2 (as far as we can tell).

Dirk-Jan and Matthijs mentioned that this issue would be looked into further at the venus-platform end, and then once venus-platform exposes that "invert" value, gui-v2 will need to consume it in order to perform the fallback "level" calculation properly.

**Comment by dirkjanfaber** [comment]
This got solved via a [TOPDOWN](https://github.com/victronenergy/dbus-ble-sensors/blob/master/src/mopeka.c#L426) bit in the configuration for certain (Mopeka) sensors. Apart from switching the logic when the bit is set, it also [adds some specific configuration](https://github.com/victronenergy/dbus-ble-sensors/blob/master/src/mopeka.c#L144) for this type of sensor (`RawValueEmpty` and `RawValueFull`, see [here](https://github.com/victronenergy/dbus-ble-sensors/blob/master/src/mopeka.c#L98)). These 2 extra configuration options are already supported in gui-v2 (See [here](https://github.com/victronenergy/gui-v2/blob/main/pages/settings/devicelist/tank/PageTankSetup.qml#L58)). 

So this issue can safely be closed.
