### ISSUE TITLE
Add empty state views where applicable

### ISSUE THREAD

**Issue by blammit** [victronenergy/gui-v2#946]
See Figma. Serj has provided empty state views, with specific examples for:

- Generator start/stop settings, when there is no generator
- Wi-Fi settings, when no adaptor is connected
- Levels page, when there are no tanks or environment sensors
- Overview page, when there are no left-hand boxes (i.e. no AC inputs, DC inputs or PV devices)

As part of this task, investigate other cases where these can be used.

**Comment by jpetrell** [comment]
I have been discussing the empty states with Serj as part of #723. There hasn't been empty state design before really, which has resulted different views implementing the empty state in their own way.

**Comment by jpetrell** [comment]
Marking as duplicate.

**Comment by blammit** [comment]
> I have been discussing the empty states with Serj as part of #723. There hasn't been empty state design before really, which has resulted different views implementing the empty state in their own way.

Ah! Thanks :)
