### ISSUE TITLE
Brief page layout doesn't work well on installations with only few sensors

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#987]
If you don't have many sensors the Brief page looks quite bare, "big hole in the display is not appealing". Reported by community and Nick.

![image](https://github.com/victronenergy/gui-v2/assets/2203667/d13f2dab-0757-493e-a848-0a2ab117653b)

**Comment by blammit** [comment]
This will be resolved/tracked separately as part of adding more battery details in the center.
