### ISSUE TITLE
Label alignment and overlap issues with Chinese, Arabic and Thai scripts

### ISSUE THREAD

**Issue by jpetrell** [victronenergy/gui-v2#993]
Due to difference in non-Latin and Museo Sans font metrics the unit labels don't align and some labels are drawn outside their boxes in the Overview page. See Thai examples below. Similar issues also appear on Chinese and Arabic, and to lesser extent in Cyrillic scripts (e.g. Ukrainian).

The Overview page has bunch of labels drawn outside their boxes:
![image](https://github.com/victronenergy/gui-v2/assets/2203667/024d63f3-fd9b-42ce-9fc3-517305063de6)

~~The Brief page shows unit label "W" having different base line to the value label (e.g. -303)~~: **Fixed**
![image](https://github.com/victronenergy/gui-v2/assets/2203667/7ed3aac8-61c0-4896-a546-db129bc58413)

**Comment by blammit** [comment]
Unit labels are no longer overlapping as QuantityLabel has been reworked. Not reproducible in 1.0.0. Closing.
